In [1]:
import os
import pandas as pd
import bev
import cv2
import numpy as np
from tqdm import tqdm
import json
import time
import torch
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [2]:
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'TRUE'

In [3]:
# Constants

NUM_ROWS = 4096

DATASET_PATH = "../../../dataset"
IMAGES_A_PATH = os.path.join(DATASET_PATH, 'images_A')
IMAGES_B_PATH = os.path.join(DATASET_PATH, 'images_B')
METADATA_PATH = os.path.join(DATASET_PATH, 'metadata_A')

DATAFRAME_PATH = "../../eval"
SAVE_PATH = os.path.join(DATAFRAME_PATH, "pipeline_results.csv")

MODEL_PATH = "../../models/pose_landmarker_full.task"

FOCAL_LENGTH_MM = 35.0
SENSOR_WIDTH_MM = 36.0
IMAGE_HEIGHT_PX = 1080
IMAGE_WIDTH_PX = 1920
BASELINE_M = 0.1

In [4]:
# Load Dataframe

df = pd.read_csv(SAVE_PATH, dtype={'id': str})
df.head(6)

,id,actor,pose,cam_pitch,gt_dist,gt_ang_sep,gt_d_yaw,gt_d_pitch,gt_sw_x,gt_sw_y,...,m2pa_dist,m2pa_ang_sep,m2pa_d_yaw,m2pa_d_pitch,m2pa_sw_x,m2pa_sw_y,m2pa_sw_z,m2pa_sc_x,m2pa_sc_y,m2pa_sc_z
0,00001,BP_Ada_C_1,34.0,-6.287881,354.167297,14.391177,-4.068234,13.838668,-0.968621,0.066612,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00002,BP_Ada_C_1,17.0,-80.392527,839.159817,70.426628,10.291927,-70.265796,-0.335014,-0.175880,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00003,BP_Ada_C_1,114.0,-50.585528,716.956094,30.322529,-20.436334,29.535145,-0.863197,0.059908,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00004,BP_Ada_C_1,42.0,-20.623707,357.440408,61.804887,-68.575333,9.502579,-0.472476,0.805154,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00005,BP_Ada_C_1,114.0,-16.400097,540.643029,72.647749,82.989366,63.720576,-0.298245,-0.170291,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,00006,BP_Ada_C_1,92.0,-67.072543,511.871710,35.985887,-115.477473,3.051334,-0.809162,0.306925,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# Configure BEV Settings

settings = bev.main.default_settings
settings.mode = 'image'
settings.render_mesh = False  # Skip the 3D mesh creation
settings.show = False         # Skip opening a display window
settings.save_dict = False    # Skip saving .npz files to disk

In [6]:
# Load BEV Model

bev_model = bev.BEV(settings)

Using BEV.
Threshold for positive center detection: 0.08

c:\Users\ExoHorizon\miniconda3\envs\fbv-bev\lib\site-packages\bev\main.py:101: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(self.settings.model_path, map_location=self.tdevice), strict=False)
c:\Users\ExoHorizon\miniconda3\envs\fbv-bev\lib\site-packages\romp\smpl.py:41: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model_info = torch.load(model_path)

In [7]:
def run_model_pipeline(sample_id, camera_pitch_rad):
    # Load JSON Metadata
    json_path = F"{METADATA_PATH}/{sample_id}A.json"
    with open(json_path, 'r') as file:
        raw_data = json.load(file)

    data = {
        'RS': np.array([raw_data['Right Shoulder Coords'][axis] for axis in ['x', 'y', 'z']]),
        'LS': np.array([raw_data['Left Shoulder Coords'][axis] for axis in ['x', 'y', 'z']]),
        'RT': np.array([raw_data['Right Thigh Coords'][axis] for axis in ['x', 'y', 'z']]),
        'LT': np.array([raw_data['Left Thigh Coords'][axis] for axis in ['x', 'y', 'z']]),
        'RW': np.array([raw_data['Right Wrist Coords'][axis] for axis in ['x', 'y', 'z']]),
    }

    # Get Ground Truth Torso Measurements
    shoulder_midpoint = (data['RS'] + data['LS']) / 2
    thigh_midpoint = (data['RT'] + data['LT']) / 2

    shoulder_width = np.linalg.norm(data['RS'] - data['LS'])
    thigh_width = np.linalg.norm(data['RT'] - data['LT'])
    arm_length = np.linalg.norm(data['RS'] - data['RW'])
    torso_height = np.linalg.norm(shoulder_midpoint - thigh_midpoint)

    # Load Image
    image_A_path = F"{IMAGES_A_PATH}/{sample_id}A.png"
    img = cv2.imread(image_A_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    start_time = time.perf_counter()
    # ------------------------------------

    # Run Inference
    outputs = bev_model(img)
    joints = outputs['joints']
    if hasattr(joints, 'detach'):
        joints =  joints.detach().cpu().numpy()

    if joints is None or joints.size == 0:
        return [np.nan] * 10, 0
    
    #   Get 2D Keypoints
    def get_normalized_2d_keypoints(outputs, person_idx=0):
        cam = outputs['cam'][person_idx]
        if hasattr(cam, 'detach'):
            cam = cam.detach().cpu().numpy()
            
        scale = cam[0]
        trans = cam[1:3]

        joints_3d = outputs['joints'][person_idx]
        if hasattr(joints_3d, 'detach'):
            joints_3d = joints_3d.detach().cpu().numpy()
        
        kp2d_ndc = scale * (joints_3d[:, :2] + trans)

        keypoints_2d_norm = (kp2d_ndc + 1.0) / 2.0
        
        return keypoints_2d_norm

    keypoints_2d = get_normalized_2d_keypoints(outputs)

    # Create Numpy Arrays
    keypoints_3d = joints[0].copy()

    # Get Predicted Torso Measurements

    L_SHOULDER, R_SHOULDER = 16, 17
    L_HIP, R_HIP = 1, 2
    R_WRIST = 21

    model_shoulder_dist = np.linalg.norm(keypoints_3d[L_SHOULDER] - keypoints_3d[R_SHOULDER])*100
    model_arm_length = np.linalg.norm(keypoints_3d[R_WRIST] - keypoints_3d[R_SHOULDER])*100

    model_shoulder_mid = (keypoints_3d[L_SHOULDER] + keypoints_3d[R_SHOULDER]) / 2
    model_hip_mid = (keypoints_3d[L_HIP] + keypoints_3d[R_HIP]) / 2
    model_torso_height = np.linalg.norm(model_shoulder_mid - model_hip_mid)*100
    
    # Compute Scale Factor
    ratios = []
    if model_shoulder_dist > 0: ratios.append(shoulder_width / model_shoulder_dist)
    if model_arm_length > 0: ratios.append(arm_length / model_arm_length)
    if model_torso_height > 0: ratios.append(torso_height / model_torso_height)

    if not ratios:
        return [np.nan] * 10, 0

    scale_factor = np.median(ratios)

    # Scale 3D Keypoints
    keypoints_3d_cm = keypoints_3d * 100 * scale_factor

    # Calculate Pixel Focal Length
    focal_length_px = (FOCAL_LENGTH_MM * IMAGE_WIDTH_PX) / SENSOR_WIDTH_MM

    # Get Pixel Distances
    def get_pix_dist(idx1, idx2):
        p1 = keypoints_2d[idx1] * [IMAGE_WIDTH_PX, IMAGE_HEIGHT_PX]
        p2 = keypoints_2d[idx2] * [IMAGE_WIDTH_PX, IMAGE_HEIGHT_PX]
        return np.linalg.norm(p1 - p2)

    sh_mid_2d = (keypoints_2d[L_SHOULDER] + keypoints_2d[R_SHOULDER]) / 2 * [IMAGE_WIDTH_PX, IMAGE_HEIGHT_PX]
    hi_mid_2d = (keypoints_2d[L_HIP] + keypoints_2d[R_HIP]) / 2 * [IMAGE_WIDTH_PX, IMAGE_HEIGHT_PX]

    pixels_shoulders = get_pix_dist(L_SHOULDER, R_SHOULDER)
    pixels_arm = get_pix_dist(R_SHOULDER, R_WRIST)
    pixels_torso = np.linalg.norm(sh_mid_2d - hi_mid_2d)

    # Calculate Distances
    z_estimates = [
        (np.linalg.norm(keypoints_3d_cm[L_SHOULDER] - keypoints_3d_cm[R_SHOULDER]) * focal_length_px) / pixels_shoulders,
        (np.linalg.norm(keypoints_3d_cm[R_SHOULDER] - keypoints_3d_cm[R_WRIST]) * focal_length_px) / pixels_arm,
        (np.linalg.norm(model_shoulder_mid*100*scale_factor - model_hip_mid*100*scale_factor) * focal_length_px) / pixels_torso
    ]

    final_z_distance_cm = np.median(z_estimates)

    hip_center_2d = (keypoints_2d[L_HIP] + keypoints_2d[R_HIP]) / 2
    pixel_x_offset = (hip_center_2d[0] * IMAGE_WIDTH_PX) - (IMAGE_WIDTH_PX / 2)
    pixel_y_offset = (hip_center_2d[1] * IMAGE_HEIGHT_PX) - (IMAGE_HEIGHT_PX / 2)

    final_x_distance_cm = (pixel_x_offset * final_z_distance_cm) / focal_length_px
    final_y_distance_cm = (pixel_y_offset * final_z_distance_cm) / focal_length_px


    # Transform To Camera Coordinates
    transformed_keypoints_3d = keypoints_3d_cm.copy()
    transformed_keypoints_3d[:, 0] += final_x_distance_cm
    transformed_keypoints_3d[:, 1] += final_y_distance_cm
    transformed_keypoints_3d[:, 2] += final_z_distance_cm
    transformed_keypoints_3d /= 100

    # ------------------------------------
    inference_time = time.perf_counter() - start_time

    # Apply Coordinate Conversion
    def convert_to_unreal_coords(points_3d_meters):
        unreal_pts = np.zeros_like(points_3d_meters)
        unreal_pts[:, 0] = points_3d_meters[:, 2] * 100
        unreal_pts[:, 1] = points_3d_meters[:, 0] * 100
        unreal_pts[:, 2] = -points_3d_meters[:, 1] * 100
        return unreal_pts

    ue_keypoints_3d = convert_to_unreal_coords(transformed_keypoints_3d)

    # Given Constants
    camera_coords = np.array([0, 0, 0])
    world_up = np.array([0, 0, 1])

    # Get Right Shoulder & Wrist Coordinates
    shoulder_coords = ue_keypoints_3d[17]
    wrist_coords = ue_keypoints_3d[21]

    # Shoulder-Camera Distance
    distance = np.linalg.norm(shoulder_coords)

    # Shoulder-Wrist Shoulder-Camera Vectors
    shoulder_wrist = wrist_coords - shoulder_coords
    shoulder_wrist /= np.linalg.norm(shoulder_wrist)

    shoulder_camera = camera_coords - shoulder_coords
    shoulder_camera /= np.linalg.norm(shoulder_camera)

    # Angular Separation
    angular_separation_rad = np.arccos(np.clip(np.dot(shoulder_wrist, shoulder_camera), -1.0, 1.0))
    angular_separation_deg = np.rad2deg(angular_separation_rad)

    # Camera Un-Pitch Matrix (Aligns Z-Axis with Gravity)
    c, s = np.cos(-camera_pitch_rad), np.sin(-camera_pitch_rad)
    unpitch_matrix = np.array([
        [c,  0, s],
        [0,  1, 0],
        [-s, 0, c]
    ])

    # Un-Pitch Vectors
    shoulder_wrist_gravity = unpitch_matrix @ shoulder_wrist
    shoulder_wrist_gravity /= np.linalg.norm(shoulder_wrist_gravity)

    shoulder_camera_gravity = unpitch_matrix @ shoulder_camera
    shoulder_camera_gravity /= np.linalg.norm(shoulder_camera_gravity)

    # Yaw & Pitch Components
    shoulder_wrist_gravity_yaw = np.rad2deg(np.atan2(shoulder_wrist_gravity[1], shoulder_wrist_gravity[0]))
    shoulder_wrist_gravity_pitch = np.rad2deg(np.asin(np.clip(shoulder_wrist_gravity[-1], -1.0, 1.0)))

    shoulder_camera_gravity_yaw = np.rad2deg(np.atan2(shoulder_camera_gravity[1], shoulder_camera_gravity[0]))
    shoulder_camera_gravity_pitch = np.rad2deg(np.asin(np.clip(shoulder_camera_gravity[-1], -1.0, 1.0)))

    delta_yaw = (shoulder_wrist_gravity_yaw - shoulder_camera_gravity_yaw + 180) % 360 - 180
    delta_pitch = shoulder_wrist_gravity_pitch - shoulder_camera_gravity_pitch

    # Relevant Outputs
    return distance, angular_separation_deg, delta_yaw, delta_pitch, \
           shoulder_wrist[0], shoulder_wrist[1], shoulder_wrist[2], \
           shoulder_camera[0], shoulder_camera[1], shoulder_camera[2], \
           inference_time

In [8]:
# Execution Loop

active_pipeline = 'b3ad' 
pipeline_cols = [f'{active_pipeline}_{m}' for m in ['dist', 'ang_sep', 'd_yaw', 'd_pitch', 'sw_x', 'sw_y', 'sw_z', 'sc_x', 'sc_y', 'sc_z']]

total_inference_seconds = 0.0
successful_counts = 0

print(f"Running Inference for Pipeline: {active_pipeline}")

for i in tqdm(range(len(df)), desc=f"Processing {active_pipeline}"):
    row_id = df.at[i, 'id']
    
    pitch_deg = df.at[i, 'cam_pitch']
    pitch_rad = np.deg2rad(pitch_deg)
    
    try:
        *results, elapsed = run_model_pipeline(row_id, pitch_rad)
        
        df.loc[i, pipeline_cols] = results
        
        total_inference_seconds += elapsed
        successful_counts += 1

    except Exception as e:
        # tqdm.write(f"Pipeline {active_pipeline} failed for ID {row_id}: {e}")
        continue

print(f"\nTotal Cumulative Inference Time: {total_inference_seconds:.4f} seconds")
if successful_counts > 0:
    print(f"Average per sample: {(total_inference_seconds / successful_counts) * 1000:.2f} ms")

Running Inference for Pipeline: b3ad

Processing b3ad:   8%|▊         | 337/4096 [00:32<06:02, 10.38it/s]

No person detected!

Processing b3ad:  10%|▉         | 409/4096 [00:38<05:45, 10.68it/s]

No person detected!

Processing b3ad:  10%|█         | 417/4096 [00:39<05:39, 10.83it/s]

No person detected!

Processing b3ad:  11%|█         | 435/4096 [00:41<05:30, 11.09it/s]

No person detected!

Processing b3ad:  13%|█▎        | 519/4096 [00:49<05:36, 10.64it/s]

No person detected!

Processing b3ad:  13%|█▎        | 529/4096 [00:50<05:22, 11.05it/s]

No person detected!

Processing b3ad:  14%|█▎        | 561/4096 [00:53<05:24, 10.90it/s]

No person detected!

Processing b3ad:  19%|█▊        | 762/4096 [01:12<05:15, 10.56it/s]

No person detected!

Processing b3ad:  20%|█▉        | 810/4096 [01:17<04:58, 11.00it/s]

No person detected!

Processing b3ad:  21%|██        | 840/4096 [01:19<05:05, 10.65it/s]

No person detected!

Processing b3ad:  21%|██        | 846/4096 [01:20<04:53, 11.07it/s]

No person detected!

Processing b3ad:  21%|██        | 860/4096 [01:21<04:52, 11.05it/s]

No person detected!

Processing b3ad:  26%|██▌       | 1056/4096 [01:39<04:25, 11.43it/s]

No person detected!

Processing b3ad:  26%|██▌       | 1062/4096 [01:40<04:21, 11.61it/s]

No person detected!
No person detected!

Processing b3ad:  30%|██▉       | 1216/4096 [01:54<04:21, 11.01it/s]

No person detected!

Processing b3ad:  30%|██▉       | 1228/4096 [01:56<04:20, 11.00it/s]

No person detected!

Processing b3ad:  30%|███       | 1238/4096 [01:56<04:15, 11.17it/s]

No person detected!

Processing b3ad:  33%|███▎      | 1368/4096 [02:08<04:09, 10.93it/s]

No person detected!

Processing b3ad:  37%|███▋      | 1518/4096 [02:23<03:48, 11.28it/s]

No person detected!

Processing b3ad:  39%|███▉      | 1596/4096 [02:30<03:45, 11.07it/s]

No person detected!

Processing b3ad:  43%|████▎     | 1744/4096 [02:44<03:37, 10.80it/s]

No person detected!

Processing b3ad:  43%|████▎     | 1768/4096 [02:46<03:32, 10.96it/s]

No person detected!

Processing b3ad:  43%|████▎     | 1778/4096 [02:47<03:29, 11.08it/s]

No person detected!

Processing b3ad:  46%|████▋     | 1902/4096 [02:58<03:11, 11.47it/s]

No person detected!

Processing b3ad:  47%|████▋     | 1922/4096 [03:00<03:08, 11.52it/s]

No person detected!

Processing b3ad:  49%|████▉     | 2004/4096 [03:07<03:00, 11.57it/s]

No person detected!

Processing b3ad:  50%|████▉     | 2030/4096 [03:10<03:01, 11.39it/s]

No person detected!

Processing b3ad:  50%|█████     | 2054/4096 [03:12<03:11, 10.64it/s]

No person detected!

Processing b3ad:  50%|█████     | 2056/4096 [03:12<03:10, 10.69it/s]

No person detected!

Processing b3ad:  51%|█████     | 2070/4096 [03:13<03:14, 10.40it/s]

No person detected!

Processing b3ad:  51%|█████     | 2078/4096 [03:14<03:12, 10.46it/s]

No person detected!

Processing b3ad:  51%|█████     | 2092/4096 [03:16<03:19, 10.02it/s]

No person detected!

Processing b3ad:  51%|█████▏    | 2102/4096 [03:17<03:16, 10.17it/s]

No person detected!

Processing b3ad:  51%|█████▏    | 2104/4096 [03:17<03:17, 10.10it/s]

No person detected!

Processing b3ad:  52%|█████▏    | 2114/4096 [03:18<03:10, 10.38it/s]

No person detected!

Processing b3ad:  52%|█████▏    | 2118/4096 [03:18<03:14, 10.17it/s]

No person detected!

Processing b3ad:  52%|█████▏    | 2124/4096 [03:19<03:08, 10.48it/s]

No person detected!

Processing b3ad:  52%|█████▏    | 2150/4096 [03:21<03:11, 10.18it/s]

No person detected!

Processing b3ad:  53%|█████▎    | 2170/4096 [03:23<03:00, 10.70it/s]

No person detected!

Processing b3ad:  53%|█████▎    | 2176/4096 [03:24<02:53, 11.06it/s]

No person detected!
No person detected!
No person detected!

Processing b3ad:  53%|█████▎    | 2180/4096 [03:24<03:00, 10.62it/s]

No person detected!

Processing b3ad:  53%|█████▎    | 2184/4096 [03:24<03:00, 10.59it/s]

No person detected!
No person detected!

Processing b3ad:  54%|█████▎    | 2200/4096 [03:26<02:55, 10.77it/s]

No person detected!

Processing b3ad:  54%|█████▍    | 2208/4096 [03:27<02:50, 11.08it/s]

No person detected!
No person detected!

Processing b3ad:  54%|█████▍    | 2212/4096 [03:27<02:50, 11.07it/s]

No person detected!
No person detected!

Processing b3ad:  54%|█████▍    | 2218/4096 [03:28<02:55, 10.69it/s]

No person detected!

Processing b3ad:  55%|█████▍    | 2238/4096 [03:30<02:58, 10.42it/s]

No person detected!

Processing b3ad:  55%|█████▍    | 2250/4096 [03:31<02:58, 10.34it/s]

No person detected!

Processing b3ad:  55%|█████▌    | 2258/4096 [03:31<02:51, 10.72it/s]

No person detected!

Processing b3ad:  55%|█████▌    | 2268/4096 [03:32<02:54, 10.46it/s]

No person detected!
No person detected!

Processing b3ad:  55%|█████▌    | 2272/4096 [03:33<02:50, 10.70it/s]

No person detected!
No person detected!

Processing b3ad:  56%|█████▌    | 2286/4096 [03:34<02:57, 10.19it/s]

No person detected!

Processing b3ad:  56%|█████▌    | 2290/4096 [03:35<02:53, 10.41it/s]

No person detected!

Processing b3ad:  56%|█████▋    | 2306/4096 [03:36<02:51, 10.44it/s]

No person detected!

Processing b3ad:  57%|█████▋    | 2330/4096 [03:39<02:54, 10.13it/s]

No person detected!

Processing b3ad:  57%|█████▋    | 2349/4096 [03:40<02:47, 10.46it/s]

No person detected!

Processing b3ad:  58%|█████▊    | 2367/4096 [03:42<02:51, 10.08it/s]

No person detected!

Processing b3ad:  58%|█████▊    | 2391/4096 [03:44<02:41, 10.56it/s]

No person detected!

Processing b3ad:  59%|█████▊    | 2401/4096 [03:45<02:38, 10.70it/s]

No person detected!

Processing b3ad:  60%|█████▉    | 2443/4096 [03:49<02:36, 10.56it/s]

No person detected!

Processing b3ad:  60%|█████▉    | 2447/4096 [03:50<02:34, 10.65it/s]

No person detected!

Processing b3ad:  61%|██████    | 2489/4096 [03:54<02:38, 10.15it/s]

No person detected!
No person detected!

Processing b3ad:  61%|██████    | 2491/4096 [03:54<02:39, 10.07it/s]

No person detected!

Processing b3ad:  61%|██████    | 2503/4096 [03:55<02:34, 10.31it/s]

No person detected!

Processing b3ad:  61%|██████▏   | 2517/4096 [03:57<02:34, 10.25it/s]

No person detected!

Processing b3ad:  62%|██████▏   | 2521/4096 [03:57<02:35, 10.11it/s]

No person detected!

Processing b3ad:  62%|██████▏   | 2526/4096 [03:58<02:37,  9.94it/s]

No person detected!

Processing b3ad:  62%|██████▏   | 2554/4096 [04:00<02:28, 10.36it/s]

No person detected!

Processing b3ad:  62%|██████▏   | 2556/4096 [04:01<02:25, 10.55it/s]

No person detected!

Processing b3ad:  62%|██████▎   | 2560/4096 [04:01<02:26, 10.47it/s]

No person detected!

Processing b3ad:  63%|██████▎   | 2578/4096 [04:03<02:27, 10.28it/s]

No person detected!

Processing b3ad:  63%|██████▎   | 2580/4096 [04:03<02:26, 10.32it/s]

No person detected!

Processing b3ad:  63%|██████▎   | 2594/4096 [04:04<02:26, 10.28it/s]

No person detected!

Processing b3ad:  65%|██████▌   | 2666/4096 [04:11<02:14, 10.62it/s]

No person detected!

Processing b3ad:  66%|██████▌   | 2688/4096 [04:13<02:14, 10.50it/s]

No person detected!

Processing b3ad:  66%|██████▌   | 2698/4096 [04:14<02:13, 10.50it/s]

No person detected!

Processing b3ad:  66%|██████▌   | 2700/4096 [04:15<02:18, 10.06it/s]

No person detected!

Processing b3ad:  66%|██████▌   | 2704/4096 [04:15<02:15, 10.29it/s]

No person detected!
No person detected!

Processing b3ad:  66%|██████▌   | 2712/4096 [04:16<02:14, 10.25it/s]

No person detected!

Processing b3ad:  66%|██████▋   | 2716/4096 [04:16<02:11, 10.48it/s]

No person detected!

Processing b3ad:  66%|██████▋   | 2722/4096 [04:17<02:06, 10.90it/s]

No person detected!
No person detected!

Processing b3ad:  67%|██████▋   | 2726/4096 [04:17<02:05, 10.93it/s]

No person detected!

Processing b3ad:  67%|██████▋   | 2728/4096 [04:17<02:03, 11.07it/s]

No person detected!

Processing b3ad:  67%|██████▋   | 2736/4096 [04:18<02:07, 10.69it/s]

No person detected!

Processing b3ad:  67%|██████▋   | 2738/4096 [04:18<02:04, 10.88it/s]

No person detected!

Processing b3ad:  67%|██████▋   | 2748/4096 [04:19<02:04, 10.81it/s]

No person detected!

Processing b3ad:  67%|██████▋   | 2760/4096 [04:20<02:03, 10.85it/s]

No person detected!
No person detected!

Processing b3ad:  68%|██████▊   | 2768/4096 [04:21<02:08, 10.35it/s]

No person detected!

Processing b3ad:  68%|██████▊   | 2776/4096 [04:22<02:04, 10.61it/s]

No person detected!

Processing b3ad:  68%|██████▊   | 2782/4096 [04:22<02:03, 10.62it/s]

No person detected!

Processing b3ad:  68%|██████▊   | 2788/4096 [04:23<01:58, 11.02it/s]

No person detected!
No person detected!

Processing b3ad:  68%|██████▊   | 2794/4096 [04:23<02:02, 10.66it/s]

No person detected!

Processing b3ad:  69%|██████▊   | 2810/4096 [04:25<01:58, 10.85it/s]

No person detected!
No person detected!

Processing b3ad:  69%|██████▉   | 2830/4096 [04:27<01:57, 10.76it/s]

No person detected!

Processing b3ad:  69%|██████▉   | 2836/4096 [04:27<02:02, 10.25it/s]

No person detected!

Processing b3ad:  70%|██████▉   | 2852/4096 [04:29<01:57, 10.55it/s]

No person detected!
No person detected!

Processing b3ad:  70%|███████   | 2872/4096 [04:31<01:51, 11.00it/s]

No person detected!

Processing b3ad:  70%|███████   | 2876/4096 [04:31<01:51, 10.96it/s]

No person detected!

Processing b3ad:  70%|███████   | 2884/4096 [04:32<01:50, 11.01it/s]

No person detected!

Processing b3ad:  71%|███████   | 2910/4096 [04:34<01:52, 10.58it/s]

No person detected!

Processing b3ad:  72%|███████▏  | 2934/4096 [04:37<01:55, 10.05it/s]

No person detected!

Processing b3ad:  72%|███████▏  | 2941/4096 [04:38<01:53, 10.17it/s]

No person detected!

Processing b3ad:  72%|███████▏  | 2949/4096 [04:38<01:53, 10.06it/s]

No person detected!

Processing b3ad:  72%|███████▏  | 2965/4096 [04:40<01:52, 10.08it/s]

No person detected!

Processing b3ad:  73%|███████▎  | 2977/4096 [04:41<01:46, 10.53it/s]

No person detected!

Processing b3ad:  73%|███████▎  | 2997/4096 [04:43<01:42, 10.77it/s]

No person detected!

Processing b3ad:  73%|███████▎  | 3001/4096 [04:43<01:42, 10.70it/s]

No person detected!

Processing b3ad:  73%|███████▎  | 3005/4096 [04:44<01:42, 10.66it/s]

No person detected!

Processing b3ad:  74%|███████▎  | 3019/4096 [04:45<01:44, 10.34it/s]

No person detected!

Processing b3ad:  74%|███████▍  | 3027/4096 [04:46<01:39, 10.69it/s]

No person detected!

Processing b3ad:  75%|███████▍  | 3055/4096 [04:48<01:40, 10.36it/s]

No person detected!

Processing b3ad:  75%|███████▍  | 3067/4096 [04:50<01:40, 10.24it/s]

No person detected!

Processing b3ad:  75%|███████▌  | 3087/4096 [04:52<01:37, 10.34it/s]

No person detected!
No person detected!

Processing b3ad:  75%|███████▌  | 3091/4096 [04:52<01:34, 10.63it/s]

No person detected!

Processing b3ad:  76%|███████▌  | 3117/4096 [04:54<01:34, 10.38it/s]

No person detected!

Processing b3ad:  76%|███████▋  | 3125/4096 [04:55<01:34, 10.28it/s]

No person detected!
No person detected!

Processing b3ad:  76%|███████▋  | 3129/4096 [04:56<01:30, 10.67it/s]

No person detected!
No person detected!

Processing b3ad:  77%|███████▋  | 3137/4096 [04:56<01:33, 10.28it/s]

No person detected!

Processing b3ad:  77%|███████▋  | 3139/4096 [04:57<01:32, 10.36it/s]

No person detected!

Processing b3ad:  77%|███████▋  | 3143/4096 [04:57<01:33, 10.21it/s]

No person detected!

Processing b3ad:  77%|███████▋  | 3151/4096 [04:58<01:33, 10.15it/s]

No person detected!

Processing b3ad:  77%|███████▋  | 3155/4096 [04:58<01:33, 10.10it/s]

No person detected!

Processing b3ad:  77%|███████▋  | 3167/4096 [04:59<01:27, 10.58it/s]

No person detected!
No person detected!

Processing b3ad:  78%|███████▊  | 3177/4096 [05:00<01:28, 10.40it/s]

No person detected!

Processing b3ad:  78%|███████▊  | 3181/4096 [05:01<01:31, 10.01it/s]

No person detected!

Processing b3ad:  79%|███████▊  | 3223/4096 [05:05<01:23, 10.50it/s]

No person detected!
No person detected!

Processing b3ad:  79%|███████▉  | 3227/4096 [05:05<01:22, 10.58it/s]

No person detected!

Processing b3ad:  79%|███████▉  | 3235/4096 [05:06<01:22, 10.47it/s]

No person detected!

Processing b3ad:  79%|███████▉  | 3241/4096 [05:06<01:18, 10.88it/s]

No person detected!

Processing b3ad:  79%|███████▉  | 3255/4096 [05:08<01:20, 10.43it/s]

No person detected!

Processing b3ad:  80%|███████▉  | 3271/4096 [05:09<01:20, 10.24it/s]

No person detected!

Processing b3ad:  80%|████████  | 3290/4096 [05:11<01:17, 10.45it/s]

No person detected!

Processing b3ad:  81%|████████  | 3304/4096 [05:13<01:15, 10.51it/s]

No person detected!

Processing b3ad:  81%|████████▏ | 3332/4096 [05:15<01:10, 10.80it/s]

No person detected!

Processing b3ad:  81%|████████▏ | 3336/4096 [05:16<01:09, 10.95it/s]

No person detected!
No person detected!

Processing b3ad:  82%|████████▏ | 3346/4096 [05:16<01:07, 11.03it/s]

No person detected!

Processing b3ad:  82%|████████▏ | 3350/4096 [05:17<01:09, 10.80it/s]

No person detected!

Processing b3ad:  82%|████████▏ | 3352/4096 [05:17<01:08, 10.81it/s]

No person detected!
No person detected!

Processing b3ad:  82%|████████▏ | 3360/4096 [05:18<01:10, 10.41it/s]

No person detected!

Processing b3ad:  82%|████████▏ | 3364/4096 [05:18<01:06, 11.01it/s]

No person detected!
No person detected!

Processing b3ad:  82%|████████▏ | 3368/4096 [05:18<01:05, 11.12it/s]

No person detected!
No person detected!

Processing b3ad:  82%|████████▏ | 3374/4096 [05:19<01:07, 10.70it/s]

No person detected!

Processing b3ad:  82%|████████▏ | 3378/4096 [05:19<01:05, 10.95it/s]

No person detected!
No person detected!

Processing b3ad:  83%|████████▎ | 3391/4096 [05:21<01:15,  9.33it/s]

No person detected!

Processing b3ad:  83%|████████▎ | 3396/4096 [05:21<01:12,  9.60it/s]

No person detected!

Processing b3ad:  83%|████████▎ | 3404/4096 [05:22<01:06, 10.42it/s]

No person detected!
No person detected!
No person detected!

Processing b3ad:  83%|████████▎ | 3410/4096 [05:23<01:06, 10.24it/s]

No person detected!
No person detected!

Processing b3ad:  83%|████████▎ | 3414/4096 [05:23<01:05, 10.47it/s]

No person detected!

Processing b3ad:  83%|████████▎ | 3418/4096 [05:23<01:04, 10.52it/s]

No person detected!
No person detected!

Processing b3ad:  84%|████████▎ | 3422/4096 [05:24<01:03, 10.60it/s]

No person detected!

Processing b3ad:  84%|████████▍ | 3444/4096 [05:26<01:01, 10.66it/s]

No person detected!
No person detected!

Processing b3ad:  84%|████████▍ | 3446/4096 [05:26<00:59, 10.92it/s]

No person detected!
No person detected!

Processing b3ad:  84%|████████▍ | 3454/4096 [05:27<00:59, 10.83it/s]

No person detected!

Processing b3ad:  85%|████████▍ | 3464/4096 [05:28<00:59, 10.64it/s]

No person detected!

Processing b3ad:  85%|████████▍ | 3480/4096 [05:29<00:59, 10.42it/s]

No person detected!

Processing b3ad:  85%|████████▌ | 3488/4096 [05:30<00:59, 10.28it/s]

No person detected!

Processing b3ad:  85%|████████▌ | 3494/4096 [05:31<00:56, 10.61it/s]

No person detected!
No person detected!

Processing b3ad:  85%|████████▌ | 3498/4096 [05:31<00:55, 10.71it/s]

No person detected!

Processing b3ad:  86%|████████▌ | 3506/4096 [05:32<00:54, 10.82it/s]

No person detected!

Processing b3ad:  86%|████████▌ | 3510/4096 [05:32<00:55, 10.58it/s]

No person detected!

Processing b3ad:  86%|████████▌ | 3524/4096 [05:33<00:51, 11.03it/s]

No person detected!
No person detected!

Processing b3ad:  87%|████████▋ | 3544/4096 [05:35<00:50, 10.97it/s]

No person detected!

Processing b3ad:  87%|████████▋ | 3572/4096 [05:38<00:49, 10.66it/s]

No person detected!
No person detected!

Processing b3ad:  87%|████████▋ | 3576/4096 [05:38<00:50, 10.37it/s]

No person detected!

Processing b3ad:  87%|████████▋ | 3582/4096 [05:39<00:49, 10.37it/s]

No person detected!
No person detected!

Processing b3ad:  88%|████████▊ | 3600/4096 [05:41<00:47, 10.47it/s]

No person detected!

Processing b3ad:  88%|████████▊ | 3611/4096 [05:42<00:48, 10.02it/s]

No person detected!

Processing b3ad:  88%|████████▊ | 3615/4096 [05:42<00:46, 10.25it/s]

No person detected!

Processing b3ad:  88%|████████▊ | 3619/4096 [05:43<00:47,  9.96it/s]

No person detected!
No person detected!

Processing b3ad:  89%|████████▊ | 3635/4096 [05:44<00:43, 10.51it/s]

No person detected!
No person detected!

Processing b3ad:  89%|████████▉ | 3639/4096 [05:45<00:41, 10.99it/s]

No person detected!
No person detected!

Processing b3ad:  89%|████████▉ | 3645/4096 [05:45<00:41, 10.80it/s]

No person detected!

Processing b3ad:  90%|████████▉ | 3681/4096 [05:49<00:39, 10.57it/s]

No person detected!

Processing b3ad:  90%|█████████ | 3687/4096 [05:49<00:38, 10.72it/s]

No person detected!

Processing b3ad:  90%|█████████ | 3693/4096 [05:50<00:37, 10.68it/s]

No person detected!
No person detected!

Processing b3ad:  91%|█████████ | 3737/4096 [05:54<00:32, 10.91it/s]

No person detected!

Processing b3ad:  92%|█████████▏| 3751/4096 [05:55<00:32, 10.72it/s]

No person detected!

Processing b3ad:  92%|█████████▏| 3759/4096 [05:56<00:31, 10.80it/s]

No person detected!
No person detected!

Processing b3ad:  92%|█████████▏| 3761/4096 [05:56<00:30, 10.86it/s]

No person detected!

Processing b3ad:  92%|█████████▏| 3773/4096 [05:57<00:29, 10.86it/s]

No person detected!

Processing b3ad:  92%|█████████▏| 3777/4096 [05:58<00:29, 10.80it/s]

No person detected!

Processing b3ad:  93%|█████████▎| 3799/4096 [06:00<00:27, 10.70it/s]

No person detected!

Processing b3ad:  93%|█████████▎| 3805/4096 [06:00<00:27, 10.74it/s]

No person detected!

Processing b3ad:  93%|█████████▎| 3827/4096 [06:02<00:24, 10.77it/s]

No person detected!

Processing b3ad:  94%|█████████▍| 3849/4096 [06:04<00:23, 10.64it/s]

No person detected!

Processing b3ad:  94%|█████████▍| 3859/4096 [06:05<00:21, 10.90it/s]

No person detected!

Processing b3ad:  94%|█████████▍| 3865/4096 [06:06<00:21, 10.66it/s]

No person detected!

Processing b3ad:  95%|█████████▍| 3871/4096 [06:06<00:20, 11.03it/s]

No person detected!
No person detected!

Processing b3ad:  95%|█████████▍| 3873/4096 [06:07<00:20, 10.98it/s]

No person detected!

Processing b3ad:  95%|█████████▍| 3875/4096 [06:07<00:20, 11.03it/s]

No person detected!

Processing b3ad:  95%|█████████▍| 3883/4096 [06:07<00:20, 10.54it/s]

No person detected!

Processing b3ad:  95%|█████████▍| 3887/4096 [06:08<00:19, 10.69it/s]

No person detected!
No person detected!

Processing b3ad:  95%|█████████▍| 3891/4096 [06:08<00:18, 10.82it/s]

No person detected!

Processing b3ad:  95%|█████████▌| 3893/4096 [06:08<00:18, 11.04it/s]

No person detected!

Processing b3ad:  95%|█████████▌| 3901/4096 [06:09<00:17, 10.89it/s]

No person detected!
No person detected!

Processing b3ad:  95%|█████████▌| 3911/4096 [06:10<00:17, 10.56it/s]

No person detected!

Processing b3ad:  96%|█████████▌| 3923/4096 [06:11<00:16, 10.31it/s]

No person detected!
No person detected!

Processing b3ad:  96%|█████████▌| 3933/4096 [06:12<00:15, 10.57it/s]

No person detected!

Processing b3ad:  96%|█████████▋| 3943/4096 [06:13<00:14, 10.32it/s]

No person detected!

Processing b3ad:  96%|█████████▋| 3947/4096 [06:14<00:14, 10.30it/s]

No person detected!

Processing b3ad:  97%|█████████▋| 3953/4096 [06:14<00:13, 10.27it/s]

No person detected!

Processing b3ad:  97%|█████████▋| 3957/4096 [06:14<00:13, 10.26it/s]

No person detected!

Processing b3ad:  97%|█████████▋| 3965/4096 [06:15<00:12, 10.75it/s]

No person detected!
No person detected!

Processing b3ad:  97%|█████████▋| 3969/4096 [06:16<00:11, 10.86it/s]

No person detected!

Processing b3ad:  97%|█████████▋| 3983/4096 [06:17<00:10, 10.65it/s]

No person detected!

Processing b3ad:  97%|█████████▋| 3985/4096 [06:17<00:10, 10.73it/s]

No person detected!

Processing b3ad:  98%|█████████▊| 4011/4096 [06:20<00:07, 10.79it/s]

No person detected!

Processing b3ad:  98%|█████████▊| 4017/4096 [06:20<00:07, 10.82it/s]

No person detected!

Processing b3ad:  99%|█████████▊| 4035/4096 [06:22<00:05, 10.77it/s]

No person detected!

Processing b3ad:  99%|█████████▊| 4043/4096 [06:23<00:04, 10.62it/s]

No person detected!

Processing b3ad:  99%|█████████▉| 4061/4096 [06:24<00:03, 10.68it/s]

No person detected!

Processing b3ad:  99%|█████████▉| 4069/4096 [06:25<00:02, 10.71it/s]

No person detected!

Processing b3ad:  99%|█████████▉| 4071/4096 [06:25<00:02, 10.95it/s]

No person detected!

Processing b3ad: 100%|██████████| 4096/4096 [06:28<00:00, 10.56it/s]

Total Cumulative Inference Time: 200.6276 seconds
Average per sample: 52.27 ms

In [8]:
print(df.info(verbose=True, show_counts=True))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4096 entries, 0 to 4095
Data columns (total 84 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            4096 non-null   object
 1   actor         4096 non-null   object
 2   pose          4096 non-null   float64
 3   cam_pitch     4096 non-null   float64
 4   gt_dist       4096 non-null   float64
 5   gt_ang_sep    4096 non-null   float64
 6   gt_d_yaw      4096 non-null   float64
 7   gt_d_pitch    4096 non-null   float64
 8   gt_sw_x       4096 non-null   float64
 9   gt_sw_y       4096 non-null   float64
 10  gt_sw_z       4096 non-null   float64
 11  gt_sc_x       4096 non-null   float64
 12  gt_sc_y       4096 non-null   float64
 13  gt_sc_z       4096 non-null   float64
 14  b3ad_dist     3937 non-null   float64
 15  b3ad_ang_sep  3937 non-null   float64
 16  b3ad_d_yaw    3937 non-null   float64
 17  b3ad_d_pitch  3937 non-null   float64
 18  b3ad_sw_x     3937 non-null   float64
 19  b3ad_sw_y     3937 non-null   float64
 20  b3ad_sw_z     3937 non-null   float64
 21  b3ad_sc_x     3937 non-null   float64
 22  b3ad_sc_y     3937 non-null   float64
 23  b3ad_sc_z     3937 non-null   float64
 24  b3sd_dist     0 non-null      float64
 25  b3sd_ang_sep  0 non-null      float64
 26  b3sd_d_yaw    0 non-null      float64
 27  b3sd_d_pitch  0 non-null      float64
 28  b3sd_sw_x     0 non-null      float64
 29  b3sd_sw_y     0 non-null      float64
 30  b3sd_sw_z     0 non-null      float64
 31  b3sd_sc_x     0 non-null      float64
 32  b3sd_sc_y     0 non-null      float64
 33  b3sd_sc_z     0 non-null      float64
 34  m3ad_dist     2307 non-null   float64
 35  m3ad_ang_sep  2307 non-null   float64
 36  m3ad_d_yaw    2307 non-null   float64
 37  m3ad_d_pitch  2307 non-null   float64
 38  m3ad_sw_x     2307 non-null   float64
 39  m3ad_sw_y     2307 non-null   float64
 40  m3ad_sw_z     2307 non-null   float64
 41  m3ad_sc_x     2307 non-null   float64
 42  m3ad_sc_y     2307 non-null   float64
 43  m3ad_sc_z     2307 non-null   float64
 44  m3sd_dist     2277 non-null   float64
 45  m3sd_ang_sep  2277 non-null   float64
 46  m3sd_d_yaw    2277 non-null   float64
 47  m3sd_d_pitch  2277 non-null   float64
 48  m3sd_sw_x     2277 non-null   float64
 49  m3sd_sw_y     2277 non-null   float64
 50  m3sd_sw_z     2277 non-null   float64
 51  m3sd_sc_x     2277 non-null   float64
 52  m3sd_sc_y     2277 non-null   float64
 53  m3sd_sc_z     2277 non-null   float64
 54  m2as_dist     0 non-null      float64
 55  m2as_ang_sep  0 non-null      float64
 56  m2as_d_yaw    0 non-null      float64
 57  m2as_d_pitch  0 non-null      float64
 58  m2as_sw_x     0 non-null      float64
 59  m2as_sw_y     0 non-null      float64
 60  m2as_sw_z     0 non-null      float64
 61  m2as_sc_x     0 non-null      float64
 62  m2as_sc_y     0 non-null      float64
 63  m2as_sc_z     0 non-null      float64
 64  m2st_dist     0 non-null      float64
 65  m2st_ang_sep  0 non-null      float64
 66  m2st_d_yaw    0 non-null      float64
 67  m2st_d_pitch  0 non-null      float64
 68  m2st_sw_x     0 non-null      float64
 69  m2st_sw_y     0 non-null      float64
 70  m2st_sw_z     0 non-null      float64
 71  m2st_sc_x     0 non-null      float64
 72  m2st_sc_y     0 non-null      float64
 73  m2st_sc_z     0 non-null      float64
 74  m2pa_dist     0 non-null      float64
 75  m2pa_ang_sep  0 non-null      float64
 76  m2pa_d_yaw    0 non-null      float64
 77  m2pa_d_pitch  0 non-null      float64
 78  m2pa_sw_x     0 non-null      float64
 79  m2pa_sw_y     0 non-null      float64
 80  m2pa_sw_z     0 non-null      float64
 81  m2pa_sc_x     0 non-null      float64
 82  m2pa_sc_y     0 non-null      float64
 83  m2pa_sc_z     0 non-null      float64
dtypes: float64(82), object(2)
memory usage: 2.6+ MB
None

In [9]:
pd.set_option('display.max_columns', None)
df.head(10)

,id,actor,pose,cam_pitch,gt_dist,gt_ang_sep,gt_d_yaw,gt_d_pitch,gt_sw_x,gt_sw_y,gt_sw_z,gt_sc_x,gt_sc_y,gt_sc_z,b3ad_dist,b3ad_ang_sep,b3ad_d_yaw,b3ad_d_pitch,b3ad_sw_x,b3ad_sw_y,b3ad_sw_z,b3ad_sc_x,b3ad_sc_y,b3ad_sc_z,b3sd_dist,b3sd_ang_sep,b3sd_d_yaw,b3sd_d_pitch,b3sd_sw_x,b3sd_sw_y,b3sd_sw_z,b3sd_sc_x,b3sd_sc_y,b3sd_sc_z,m3ad_dist,m3ad_ang_sep,m3ad_d_yaw,m3ad_d_pitch,m3ad_sw_x,m3ad_sw_y,m3ad_sw_z,m3ad_sc_x,m3ad_sc_y,m3ad_sc_z,m3sd_dist,m3sd_ang_sep,m3sd_d_yaw,m3sd_d_pitch,m3sd_sw_x,m3sd_sw_y,m3sd_sw_z,m3sd_sc_x,m3sd_sc_y,m3sd_sc_z,m2as_dist,m2as_ang_sep,m2as_d_yaw,m2as_d_pitch,m2as_sw_x,m2as_sw_y,m2as_sw_z,m2as_sc_x,m2as_sc_y,m2as_sc_z,m2st_dist,m2st_ang_sep,m2st_d_yaw,m2st_d_pitch,m2st_sw_x,m2st_sw_y,m2st_sw_z,m2st_sc_x,m2st_sc_y,m2st_sc_z,m2pa_dist,m2pa_ang_sep,m2pa_d_yaw,m2pa_d_pitch,m2pa_sw_x,m2pa_sw_y,m2pa_sw_z,m2pa_sc_x,m2pa_sc_y,m2pa_sc_z
0,00001,BP_Ada_C_1,34.0,-6.287881,354.167297,14.391177,-4.068234,13.838668,-0.968621,0.066612,0.239448,-1.0,8.827433e-16,2.006235e-17,585.174945,39.345997,-29.096792,28.461256,-0.800313,0.388789,0.456446,-0.999042,-0.027048,-0.034394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,637.021029,14.850775,-15.034202,0.433168,-0.969154,0.240048,0.055837,-0.998849,-0.016484,0.045054,339.393950,14.267933,-14.078275,3.014588,-0.969154,0.240048,0.055837,-1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00002,BP_Ada_C_1,17.0,-80.392527,839.159817,70.426628,10.291927,-70.265796,-0.335014,-0.175880,-0.925652,-1.0,-1.058414e-17,3.386925e-17,1913.251864,109.699960,11.003982,-109.546262,0.327019,-0.159929,-0.931387,-0.999943,0.001403,0.010596,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00003,BP_Ada_C_1,114.0,-50.585528,716.956094,30.322529,-20.436334,29.535145,-0.863197,0.059908,0.501300,-1.0,2.477637e-18,-7.928438e-17,1704.993278,169.140734,-166.090185,-94.061589,0.979394,0.180510,0.090572,-0.999849,-0.008058,-0.015365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00004,BP_Ada_C_1,42.0,-20.623707,357.440408,61.804887,-68.575333,9.502579,-0.472476,0.805154,0.358460,-1.0,3.975727e-17,3.975727e-17,671.772309,62.328035,-67.859639,8.661009,-0.493566,0.814348,0.305337,-0.999181,-0.022767,-0.033448,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,347.132425,83.777625,-86.829968,-9.904850,-0.116742,0.983634,0.137240,-0.999842,-0.006147,-0.016684,353.870463,83.295862,-86.455927,-10.861209,-0.116742,0.983634,0.137240,-1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00005,BP_Ada_C_1,114.0,-16.400097,540.643029,72.647749,82.989366,63.720576,-0.298245,-0.170291,0.939176,-1.0,1.577106e-16,1.051404e-16,738.493714,92.781332,119.979303,44.300243,0.017631,-0.451204,0.892247,-0.999042,-0.013678,-0.041560,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,542.156821,59.253452,50.104056,48.555979,-0.519870,-0.336814,0.785043,-0.999870,-0.007647,-0.014186,533.333349,58.676487,50.558918,47.742675,-0.519870,-0.336814,0.785043,-1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,00006,BP_Ada_C_1,92.0,-67.072543,511.871710,35.985887,-115.477473,3.051334,-0.809162,0.306925,0.501053,-1.0,-2.082190e-17,-5.552506e-17,1534.161531,63.127304,-99.797870,-32.114511,-0.457691,0.817597,0.349363,-0.999826,0.001096,-0.018599,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1256.007345,115.512248,-137.822760,-74.508567,0.412396,0.685860,0.599605,-0.999785,-0.012130,-0.016806,504.504538,114.355451,-136.107103,-75.481126,0.412396,0.685860,0.599605,-1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,00007,BP_Ada_C_1,115.0,-58.337415,573.534355,30.892326,77.429488,21.783261,-0.858134,-0.167461,0.485349,-1.0,1.378259e-16,1.982215e-16,995.070274,76.233570,46.385530,-66.094685,-0.225153,-0.707567,-0.669817,-0.999666,0.005671,-0.025230,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,822.190601,34.329966,93.146021,17.330402,-0.817285,-0.236138,0.525627,-0.999869,-0.011744,0.011133,565.656567,35.186024,94.451448,17.961757,-0.817285,-0.236138,0.525627,-1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,00008,BP_Ada_C_1,65.0,-83.698078,893.154696,40.795695,-94.703134,-33.572474,-0.757044,0.638948,0.136490,-1.0,-2.386628e-17,3.500388e-16,2046.226095,81.025875,23.559446,-80.425716,-0.148040,-0.267501,-0.952117,-0.999762,0.017339,-0.013257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,00009,BP_Ada_C_1,4.0,-17.160619,582.529679,90.029656,-90.070230,-17.033701,0.000518,0.999997,0.002478,-1.0,0.000000e+00,9.758030e-17,969.385163,76.166902,-70.462317,-31.006358,-0.240597,0.904900,-0.351097,-0.999595,-0.011635,-0.025986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,545.917287,86.839673,-79.581904,-38.431548,-0.054264,0.909512,-0.412119,-0.999850,-0.006345,-0.016123,583.333349,86.889360,-79.203276,-39.355726,-0.054264,0.909512,-0.412119,-1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,00010,BP_Ada_C_1,63.0,-12.268837,727.370530,37.593015,28.693427,27.857188,-0.792364,-0.367116,0.487222,-1.0,2.344476e-16,0.000000e+00,1212.800294,44.279952,36.991295,30.176196,-0.728645,-0.450227,0.516112,-0.999771,0.003667,-0.021100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1078.281027,20.779904,19.248223,9.956668,-0.928465,-0.311714,0.201956,-0.999793,-0.009901,0.017780,717.948723,21.803163,19.831148,10.974806,-0.928465,-0.311714,0.201956,-1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Save Dataframe

df.to_csv(SAVE_PATH, index=False)

In [11]:
# Sanity Check

check_df = pd.read_csv(SAVE_PATH, dtype={'id': str})
print(check_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4096 entries, 0 to 4095
Data columns (total 84 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            4096 non-null   object
 1   actor         4096 non-null   object
 2   pose          4096 non-null   float64
 3   cam_pitch     4096 non-null   float64
 4   gt_dist       4096 non-null   float64
 5   gt_ang_sep    4096 non-null   float64
 6   gt_d_yaw      4096 non-null   float64
 7   gt_d_pitch    4096 non-null   float64
 8   gt_sw_x       4096 non-null   float64
 9   gt_sw_y       4096 non-null   float64
 10  gt_sw_z       4096 non-null   float64
 11  gt_sc_x       4096 non-null   float64
 12  gt_sc_y       4096 non-null   float64
 13  gt_sc_z       4096 non-null   float64
 14  b3ad_dist     3981 non-null   float64
 15  b3ad_ang_sep  3981 non-null   float64
 16  b3ad_d_yaw    3981 non-null   float64
 17  b3ad_d_pitch  3981 non-null   float64
 18  b3ad_sw_x     3981 non-null   float64
 19  b3ad_sw_y     3981 non-null   float64
 20  b3ad_sw_z     3981 non-null   float64
 21  b3ad_sc_x     3981 non-null   float64
 22  b3ad_sc_y     3981 non-null   float64
 23  b3ad_sc_z     3981 non-null   float64
 24  b3sd_dist     0 non-null      float64
 25  b3sd_ang_sep  0 non-null      float64
 26  b3sd_d_yaw    0 non-null      float64
 27  b3sd_d_pitch  0 non-null      float64
 28  b3sd_sw_x     0 non-null      float64
 29  b3sd_sw_y     0 non-null      float64
 30  b3sd_sw_z     0 non-null      float64
 31  b3sd_sc_x     0 non-null      float64
 32  b3sd_sc_y     0 non-null      float64
 33  b3sd_sc_z     0 non-null      float64
 34  m3ad_dist     2307 non-null   float64
 35  m3ad_ang_sep  2307 non-null   float64
 36  m3ad_d_yaw    2307 non-null   float64
 37  m3ad_d_pitch  2307 non-null   float64
 38  m3ad_sw_x     2307 non-null   float64
 39  m3ad_sw_y     2307 non-null   float64
 40  m3ad_sw_z     2307 non-null   float64
 41  m3ad_sc_x     2307 non-null   float64
 42  m3ad_sc_y     2307 non-null   float64
 43  m3ad_sc_z     2307 non-null   float64
 44  m3sd_dist     2277 non-null   float64
 45  m3sd_ang_sep  2277 non-null   float64
 46  m3sd_d_yaw    2277 non-null   float64
 47  m3sd_d_pitch  2277 non-null   float64
 48  m3sd_sw_x     2277 non-null   float64
 49  m3sd_sw_y     2277 non-null   float64
 50  m3sd_sw_z     2277 non-null   float64
 51  m3sd_sc_x     2277 non-null   float64
 52  m3sd_sc_y     2277 non-null   float64
 53  m3sd_sc_z     2277 non-null   float64
 54  m2as_dist     0 non-null      float64
 55  m2as_ang_sep  0 non-null      float64
 56  m2as_d_yaw    0 non-null      float64
 57  m2as_d_pitch  0 non-null      float64
 58  m2as_sw_x     0 non-null      float64
 59  m2as_sw_y     0 non-null      float64
 60  m2as_sw_z     0 non-null      float64
 61  m2as_sc_x     0 non-null      float64
 62  m2as_sc_y     0 non-null      float64
 63  m2as_sc_z     0 non-null      float64
 64  m2st_dist     0 non-null      float64
 65  m2st_ang_sep  0 non-null      float64
 66  m2st_d_yaw    0 non-null      float64
 67  m2st_d_pitch  0 non-null      float64
 68  m2st_sw_x     0 non-null      float64
 69  m2st_sw_y     0 non-null      float64
 70  m2st_sw_z     0 non-null      float64
 71  m2st_sc_x     0 non-null      float64
 72  m2st_sc_y     0 non-null      float64
 73  m2st_sc_z     0 non-null      float64
 74  m2pa_dist     0 non-null      float64
 75  m2pa_ang_sep  0 non-null      float64
 76  m2pa_d_yaw    0 non-null      float64
 77  m2pa_d_pitch  0 non-null      float64
 78  m2pa_sw_x     0 non-null      float64
 79  m2pa_sw_y     0 non-null      float64
 80  m2pa_sw_z     0 non-null      float64
 81  m2pa_sc_x     0 non-null      float64
 82  m2pa_sc_y     0 non-null      float64
 83  m2pa_sc_z     0 non-null      float64
dtypes: float64(82), object(2)
memory usage: 2.6+ MB
None