In [1]:
import os
import pandas as pd
import bev
import cv2
import numpy as np
from tqdm import tqdm
import json
import time
import torch
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [2]:
import os
os.environ['KMP_DUPLICATE_LIB_OK'] = 'TRUE'

In [3]:
# Constants

NUM_ROWS = 8192

DATASET_PATH = "../../../dataset"
IMAGES_A_PATH = os.path.join(DATASET_PATH, 'images_A')
IMAGES_B_PATH = os.path.join(DATASET_PATH, 'images_B')
METADATA_PATH = os.path.join(DATASET_PATH, 'metadata_A')

DATAFRAME_PATH = "../../eval"
SAVE_PATH = os.path.join(DATAFRAME_PATH, "pipeline_results.csv")

MODEL_PATH = "../../models/pose_landmarker_full.task"

FOCAL_LENGTH_MM = 35.0
SENSOR_WIDTH_MM = 36.0
IMAGE_HEIGHT_PX = 1080
IMAGE_WIDTH_PX = 1920
BASELINE_M = 0.1

In [4]:
# Load Dataframe

df = pd.read_csv(SAVE_PATH, dtype={'id': str})
df.head(6)

,id,actor,pose,cam_pitch,gt_dist,gt_ang_sep,gt_d_yaw,gt_d_pitch,gt_sw_x,gt_sw_y,...,m2st_dist,m2st_ang_sep,m2st_d_yaw,m2st_d_pitch,m2st_sw_x,m2st_sw_y,m2st_sw_z,m2st_sc_x,m2st_sc_y,m2st_sc_z
0,00001,BP_Ada_C_1,34.0,-6.287881,354.167297,14.391177,-4.068234,13.838668,-0.968621,0.066612,...,337.681453,160.060166,-172.649296,7.383960,0.935750,0.127283,0.328893,-0.999921,-0.002682,-0.012263
1,00002,BP_Ada_C_1,17.0,-80.392527,839.159817,70.426628,10.291927,-70.265796,-0.335014,-0.175880,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00003,BP_Ada_C_1,114.0,-50.585528,716.956094,30.322529,-20.436334,29.535145,-0.863197,0.059908,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00004,BP_Ada_C_1,42.0,-20.623707,357.440408,61.804887,-68.575333,9.502579,-0.472476,0.805154,...,386.860524,16.545744,-17.400630,3.438862,-0.960390,0.272383,0.058802,-0.999872,-0.002752,-0.015739
4,00005,BP_Ada_C_1,114.0,-16.400097,540.643029,72.647749,82.989366,63.720576,-0.298245,-0.170291,...,483.475293,165.921985,175.796565,-18.033845,0.967381,-0.071326,0.243077,-0.999933,-0.001848,-0.011442
5,00006,BP_Ada_C_1,92.0,-67.072543,511.871710,35.985887,-115.477473,3.051334,-0.809162,0.306925,...,452.631735,175.191351,-172.912755,-127.839991,0.994123,0.070675,0.081999,-0.999674,-0.011433,-0.022845

In [5]:
# Configure BEV Settings

settings = bev.main.default_settings
settings.mode = 'image'
settings.render_mesh = False  # Skip the 3D mesh creation
settings.show = False         # Skip opening a display window
settings.save_dict = False    # Skip saving .npz files to disk

In [6]:
# Load BEV Model

bev_model = bev.BEV(settings)

Using BEV.
Threshold for positive center detection: 0.08

c:\Users\ExoHorizon\miniconda3\envs\fbv-bev\lib\site-packages\bev\main.py:101: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model.load_state_dict(torch.load(self.settings.model_path, map_location=self.tdevice), strict=False)
c:\Users\ExoHorizon\miniconda3\envs\fbv-bev\lib\site-packages\romp\smpl.py:41: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model_info = torch.load(model_path)

In [7]:
def run_model_pipeline(sample_id, camera_pitch_rad):
    # Load JSON Metadata
    json_path = F"{METADATA_PATH}/{sample_id}A.json"
    with open(json_path, 'r') as file:
        raw_data = json.load(file)

    data = {
        'RS': np.array([raw_data['Right Shoulder Coords'][axis] for axis in ['x', 'y', 'z']]),
        'LS': np.array([raw_data['Left Shoulder Coords'][axis] for axis in ['x', 'y', 'z']]),
        'RT': np.array([raw_data['Right Thigh Coords'][axis] for axis in ['x', 'y', 'z']]),
        'LT': np.array([raw_data['Left Thigh Coords'][axis] for axis in ['x', 'y', 'z']]),
        'RW': np.array([raw_data['Right Wrist Coords'][axis] for axis in ['x', 'y', 'z']]),
    }

    # Get Ground Truth Torso Measurements
    shoulder_midpoint = (data['RS'] + data['LS']) / 2
    thigh_midpoint = (data['RT'] + data['LT']) / 2

    shoulder_width = np.linalg.norm(data['RS'] - data['LS'])
    thigh_width = np.linalg.norm(data['RT'] - data['LT'])
    arm_length = np.linalg.norm(data['RS'] - data['RW'])
    torso_height = np.linalg.norm(shoulder_midpoint - thigh_midpoint)

    # Load Image
    image_A_path = F"{IMAGES_A_PATH}/{sample_id}A.png"
    img = cv2.imread(image_A_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    start_time = time.perf_counter()
    # ------------------------------------

    # Run Inference
    outputs = bev_model(img)
    joints = outputs['joints']
    if hasattr(joints, 'detach'):
        joints =  joints.detach().cpu().numpy()

    if joints is None or joints.size == 0:
        return [np.nan] * 10, 0
    
    #   Get 2D Keypoints
    def get_normalized_2d_keypoints(outputs, person_idx=0):
        cam = outputs['cam'][person_idx]
        if hasattr(cam, 'detach'):
            cam = cam.detach().cpu().numpy()
            
        scale = cam[0]
        trans = cam[1:3]

        joints_3d = outputs['joints'][person_idx]
        if hasattr(joints_3d, 'detach'):
            joints_3d = joints_3d.detach().cpu().numpy()
        
        kp2d_ndc = scale * (joints_3d[:, :2] + trans)

        keypoints_2d_norm = (kp2d_ndc + 1.0) / 2.0
        
        return keypoints_2d_norm

    keypoints_2d = get_normalized_2d_keypoints(outputs)

    # Create Numpy Arrays
    keypoints_3d = joints[0].copy()

    # Get Predicted Torso Measurements

    L_SHOULDER, R_SHOULDER = 16, 17
    L_HIP, R_HIP = 1, 2
    R_WRIST = 21

    model_shoulder_dist = np.linalg.norm(keypoints_3d[L_SHOULDER] - keypoints_3d[R_SHOULDER])*100
    model_arm_length = np.linalg.norm(keypoints_3d[R_WRIST] - keypoints_3d[R_SHOULDER])*100

    model_shoulder_mid = (keypoints_3d[L_SHOULDER] + keypoints_3d[R_SHOULDER]) / 2
    model_hip_mid = (keypoints_3d[L_HIP] + keypoints_3d[R_HIP]) / 2
    model_torso_height = np.linalg.norm(model_shoulder_mid - model_hip_mid)*100
    
    # Compute Scale Factor
    ratios = []
    if model_shoulder_dist > 0: ratios.append(shoulder_width / model_shoulder_dist)
    if model_arm_length > 0: ratios.append(arm_length / model_arm_length)
    if model_torso_height > 0: ratios.append(torso_height / model_torso_height)

    if not ratios:
        return [np.nan] * 10, 0

    scale_factor = np.median(ratios)

    # Scale 3D Keypoints
    keypoints_3d_cm = keypoints_3d * 100 * scale_factor

    # Calculate Pixel Focal Length
    focal_length_px = (FOCAL_LENGTH_MM * IMAGE_WIDTH_PX) / SENSOR_WIDTH_MM

    # Get Pixel Distances
    def get_pix_dist(idx1, idx2):
        p1 = keypoints_2d[idx1] * [IMAGE_WIDTH_PX, IMAGE_HEIGHT_PX]
        p2 = keypoints_2d[idx2] * [IMAGE_WIDTH_PX, IMAGE_HEIGHT_PX]
        return np.linalg.norm(p1 - p2)

    sh_mid_2d = (keypoints_2d[L_SHOULDER] + keypoints_2d[R_SHOULDER]) / 2 * [IMAGE_WIDTH_PX, IMAGE_HEIGHT_PX]
    hi_mid_2d = (keypoints_2d[L_HIP] + keypoints_2d[R_HIP]) / 2 * [IMAGE_WIDTH_PX, IMAGE_HEIGHT_PX]

    pixels_shoulders = get_pix_dist(L_SHOULDER, R_SHOULDER)
    pixels_arm = get_pix_dist(R_SHOULDER, R_WRIST)
    pixels_torso = np.linalg.norm(sh_mid_2d - hi_mid_2d)

    # Calculate Distances
    z_estimates = [
        (np.linalg.norm(keypoints_3d_cm[L_SHOULDER] - keypoints_3d_cm[R_SHOULDER]) * focal_length_px) / pixels_shoulders,
        (np.linalg.norm(keypoints_3d_cm[R_SHOULDER] - keypoints_3d_cm[R_WRIST]) * focal_length_px) / pixels_arm,
        (np.linalg.norm(model_shoulder_mid*100*scale_factor - model_hip_mid*100*scale_factor) * focal_length_px) / pixels_torso
    ]

    final_z_distance_cm = np.median(z_estimates)

    hip_center_2d = (keypoints_2d[L_HIP] + keypoints_2d[R_HIP]) / 2
    pixel_x_offset = (hip_center_2d[0] * IMAGE_WIDTH_PX) - (IMAGE_WIDTH_PX / 2)
    pixel_y_offset = (hip_center_2d[1] * IMAGE_HEIGHT_PX) - (IMAGE_HEIGHT_PX / 2)

    final_x_distance_cm = (pixel_x_offset * final_z_distance_cm) / focal_length_px
    final_y_distance_cm = (pixel_y_offset * final_z_distance_cm) / focal_length_px


    # Transform To Camera Coordinates
    transformed_keypoints_3d = keypoints_3d_cm.copy()
    transformed_keypoints_3d[:, 0] += final_x_distance_cm
    transformed_keypoints_3d[:, 1] += final_y_distance_cm
    transformed_keypoints_3d[:, 2] += final_z_distance_cm
    transformed_keypoints_3d /= 100

    # ------------------------------------
    inference_time = time.perf_counter() - start_time

    # Apply Coordinate Conversion
    def convert_to_unreal_coords(points_3d_meters):
        unreal_pts = np.zeros_like(points_3d_meters)
        unreal_pts[:, 0] = points_3d_meters[:, 2] * 100
        unreal_pts[:, 1] = points_3d_meters[:, 0] * 100
        unreal_pts[:, 2] = -points_3d_meters[:, 1] * 100
        return unreal_pts

    ue_keypoints_3d = convert_to_unreal_coords(transformed_keypoints_3d)

    # Given Constants
    camera_coords = np.array([0, 0, 0])
    world_up = np.array([0, 0, 1])

    # Get Right Shoulder & Wrist Coordinates
    shoulder_coords = ue_keypoints_3d[17]
    wrist_coords = ue_keypoints_3d[21]

    # Shoulder-Camera Distance
    distance = np.linalg.norm(shoulder_coords)

    # Shoulder-Wrist Shoulder-Camera Vectors
    shoulder_wrist = wrist_coords - shoulder_coords
    shoulder_wrist /= np.linalg.norm(shoulder_wrist)

    shoulder_camera = camera_coords - shoulder_coords
    shoulder_camera /= np.linalg.norm(shoulder_camera)

    # Angular Separation
    angular_separation_rad = np.arccos(np.clip(np.dot(shoulder_wrist, shoulder_camera), -1.0, 1.0))
    angular_separation_deg = np.rad2deg(angular_separation_rad)

    # Camera Un-Pitch Matrix (Aligns Z-Axis with Gravity)
    c, s = np.cos(-camera_pitch_rad), np.sin(-camera_pitch_rad)
    unpitch_matrix = np.array([
        [c,  0, s],
        [0,  1, 0],
        [-s, 0, c]
    ])

    # Un-Pitch Vectors
    shoulder_wrist_gravity = unpitch_matrix @ shoulder_wrist
    shoulder_wrist_gravity /= np.linalg.norm(shoulder_wrist_gravity)

    shoulder_camera_gravity = unpitch_matrix @ shoulder_camera
    shoulder_camera_gravity /= np.linalg.norm(shoulder_camera_gravity)

    # Yaw & Pitch Components
    shoulder_wrist_gravity_yaw = np.rad2deg(np.atan2(shoulder_wrist_gravity[1], shoulder_wrist_gravity[0]))
    shoulder_wrist_gravity_pitch = np.rad2deg(np.asin(np.clip(shoulder_wrist_gravity[-1], -1.0, 1.0)))

    shoulder_camera_gravity_yaw = np.rad2deg(np.atan2(shoulder_camera_gravity[1], shoulder_camera_gravity[0]))
    shoulder_camera_gravity_pitch = np.rad2deg(np.asin(np.clip(shoulder_camera_gravity[-1], -1.0, 1.0)))

    delta_yaw = (shoulder_wrist_gravity_yaw - shoulder_camera_gravity_yaw + 180) % 360 - 180
    delta_pitch = shoulder_wrist_gravity_pitch - shoulder_camera_gravity_pitch

    # Relevant Outputs
    return distance, angular_separation_deg, delta_yaw, delta_pitch, \
           shoulder_wrist[0], shoulder_wrist[1], shoulder_wrist[2], \
           shoulder_camera[0], shoulder_camera[1], shoulder_camera[2], \
           inference_time

In [8]:
# Execution Loop

active_pipeline = 'b3ad' 
pipeline_cols = [f'{active_pipeline}_{m}' for m in ['dist', 'ang_sep', 'd_yaw', 'd_pitch', 'sw_x', 'sw_y', 'sw_z', 'sc_x', 'sc_y', 'sc_z']]

total_inference_seconds = 0.0
successful_counts = 0

print(f"Running Inference for Pipeline: {active_pipeline}")

for i in tqdm(range(len(df)), desc=f"Processing {active_pipeline}"):
    row_id = df.at[i, 'id']
    
    pitch_deg = df.at[i, 'cam_pitch']
    pitch_rad = np.deg2rad(pitch_deg)
    
    try:
        *results, elapsed = run_model_pipeline(row_id, pitch_rad)
        
        df.loc[i, pipeline_cols] = results
        
        total_inference_seconds += elapsed
        successful_counts += 1

    except Exception as e:
        # tqdm.write(f"Pipeline {active_pipeline} failed for ID {row_id}: {e}")
        continue

print(f"\nTotal Cumulative Inference Time: {total_inference_seconds:.4f} seconds")
if successful_counts > 0:
    print(f"Average per sample: {(total_inference_seconds / successful_counts) * 1000:.2f} ms")

Running Inference for Pipeline: b3ad

Processing b3ad:   4%|▍         | 338/8192 [00:35<13:43,  9.54it/s]

No person detected!

Processing b3ad:   5%|▍         | 408/8192 [00:42<13:32,  9.58it/s]

No person detected!

Processing b3ad:   5%|▌         | 416/8192 [00:43<12:57, 10.00it/s]

No person detected!

Processing b3ad:   5%|▌         | 434/8192 [00:45<12:25, 10.41it/s]

No person detected!

Processing b3ad:   6%|▋         | 520/8192 [00:54<12:46, 10.01it/s]

No person detected!

Processing b3ad:   6%|▋         | 528/8192 [00:54<12:28, 10.24it/s]

No person detected!

Processing b3ad:   7%|▋         | 559/8192 [00:58<13:29,  9.43it/s]

No person detected!

Processing b3ad:   9%|▉         | 761/8192 [01:19<12:23,  9.99it/s]

No person detected!

Processing b3ad:  10%|▉         | 809/8192 [01:23<12:11, 10.10it/s]

No person detected!

Processing b3ad:  10%|█         | 839/8192 [01:26<12:29,  9.82it/s]

No person detected!

Processing b3ad:  10%|█         | 846/8192 [01:27<12:50,  9.54it/s]

No person detected!

Processing b3ad:  10%|█         | 860/8192 [01:29<12:17,  9.94it/s]

No person detected!

Processing b3ad:  13%|█▎        | 1055/8192 [01:49<11:44, 10.13it/s]

No person detected!

Processing b3ad:  13%|█▎        | 1061/8192 [01:49<11:44, 10.13it/s]

No person detected!
No person detected!

Processing b3ad:  15%|█▍        | 1216/8192 [02:05<11:28, 10.13it/s]

No person detected!

Processing b3ad:  15%|█▍        | 1227/8192 [02:07<11:31, 10.08it/s]

No person detected!

Processing b3ad:  15%|█▌        | 1237/8192 [02:08<11:19, 10.24it/s]

No person detected!

Processing b3ad:  17%|█▋        | 1369/8192 [02:21<11:30,  9.88it/s]

No person detected!

Processing b3ad:  19%|█▊        | 1519/8192 [02:37<11:47,  9.43it/s]

No person detected!

Processing b3ad:  19%|█▉        | 1597/8192 [02:45<11:14,  9.78it/s]

No person detected!

Processing b3ad:  21%|██▏       | 1744/8192 [03:00<11:28,  9.36it/s]

No person detected!

Processing b3ad:  22%|██▏       | 1768/8192 [03:03<12:07,  8.83it/s]

No person detected!

Processing b3ad:  22%|██▏       | 1778/8192 [03:04<11:12,  9.54it/s]

No person detected!

Processing b3ad:  23%|██▎       | 1901/8192 [03:17<10:58,  9.55it/s]

No person detected!

Processing b3ad:  23%|██▎       | 1922/8192 [03:19<10:55,  9.56it/s]

No person detected!

Processing b3ad:  24%|██▍       | 2004/8192 [03:29<11:07,  9.27it/s]

No person detected!

Processing b3ad:  25%|██▍       | 2029/8192 [03:31<10:00, 10.26it/s]

No person detected!

Processing b3ad:  25%|██▌       | 2053/8192 [03:34<10:50,  9.44it/s]

No person detected!

Processing b3ad:  25%|██▌       | 2056/8192 [03:34<11:18,  9.05it/s]

No person detected!

Processing b3ad:  25%|██▌       | 2069/8192 [03:36<12:18,  8.29it/s]

No person detected!

Processing b3ad:  25%|██▌       | 2078/8192 [03:37<11:36,  8.78it/s]

No person detected!

Processing b3ad:  26%|██▌       | 2091/8192 [03:38<11:00,  9.23it/s]

No person detected!

Processing b3ad:  26%|██▌       | 2101/8192 [03:39<12:19,  8.24it/s]

No person detected!

Processing b3ad:  26%|██▌       | 2104/8192 [03:40<12:38,  8.02it/s]

No person detected!

Processing b3ad:  26%|██▌       | 2115/8192 [03:41<10:56,  9.25it/s]

No person detected!

Processing b3ad:  26%|██▌       | 2118/8192 [03:41<11:14,  9.01it/s]

No person detected!

Processing b3ad:  26%|██▌       | 2123/8192 [03:42<12:05,  8.37it/s]

No person detected!

Processing b3ad:  26%|██▌       | 2150/8192 [03:45<10:56,  9.21it/s]

No person detected!

Processing b3ad:  26%|██▋       | 2170/8192 [03:47<11:39,  8.61it/s]

No person detected!

Processing b3ad:  27%|██▋       | 2175/8192 [03:48<11:43,  8.55it/s]

No person detected!
No person detected!

Processing b3ad:  27%|██▋       | 2177/8192 [03:48<11:47,  8.50it/s]

No person detected!

Processing b3ad:  27%|██▋       | 2179/8192 [03:48<11:24,  8.79it/s]

No person detected!

Processing b3ad:  27%|██▋       | 2183/8192 [03:49<11:15,  8.90it/s]

No person detected!
No person detected!

Processing b3ad:  27%|██▋       | 2199/8192 [03:51<11:34,  8.62it/s]

No person detected!

Processing b3ad:  27%|██▋       | 2207/8192 [03:52<10:20,  9.65it/s]

No person detected!
No person detected!

Processing b3ad:  27%|██▋       | 2211/8192 [03:52<10:21,  9.62it/s]

No person detected!
No person detected!

Processing b3ad:  27%|██▋       | 2218/8192 [03:53<10:56,  9.10it/s]

No person detected!

Processing b3ad:  27%|██▋       | 2238/8192 [03:55<11:10,  8.88it/s]

No person detected!

Processing b3ad:  27%|██▋       | 2249/8192 [03:56<11:32,  8.58it/s]

No person detected!

Processing b3ad:  28%|██▊       | 2258/8192 [03:57<11:05,  8.91it/s]

No person detected!

Processing b3ad:  28%|██▊       | 2267/8192 [03:59<11:28,  8.61it/s]

No person detected!
No person detected!

Processing b3ad:  28%|██▊       | 2272/8192 [03:59<10:36,  9.31it/s]

No person detected!
No person detected!

Processing b3ad:  28%|██▊       | 2285/8192 [04:00<11:03,  8.90it/s]

No person detected!

Processing b3ad:  28%|██▊       | 2289/8192 [04:01<11:07,  8.85it/s]

No person detected!

Processing b3ad:  28%|██▊       | 2305/8192 [04:03<11:01,  8.89it/s]

No person detected!

Processing b3ad:  28%|██▊       | 2330/8192 [04:06<10:11,  9.59it/s]

No person detected!

Processing b3ad:  29%|██▊       | 2349/8192 [04:08<10:12,  9.54it/s]

No person detected!

Processing b3ad:  29%|██▉       | 2367/8192 [04:10<10:43,  9.06it/s]

No person detected!

Processing b3ad:  29%|██▉       | 2392/8192 [04:13<11:15,  8.59it/s]

No person detected!

Processing b3ad:  29%|██▉       | 2401/8192 [04:14<10:57,  8.81it/s]

No person detected!

Processing b3ad:  30%|██▉       | 2443/8192 [04:18<10:00,  9.58it/s]

No person detected!

Processing b3ad:  30%|██▉       | 2447/8192 [04:19<10:00,  9.57it/s]

No person detected!

Processing b3ad:  30%|███       | 2489/8192 [04:24<09:58,  9.53it/s]

No person detected!
No person detected!

Processing b3ad:  30%|███       | 2491/8192 [04:24<10:29,  9.06it/s]

No person detected!

Processing b3ad:  31%|███       | 2502/8192 [04:25<10:41,  8.87it/s]

No person detected!

Processing b3ad:  31%|███       | 2517/8192 [04:27<12:06,  7.82it/s]

No person detected!

Processing b3ad:  31%|███       | 2520/8192 [04:27<11:24,  8.28it/s]

No person detected!

Processing b3ad:  31%|███       | 2526/8192 [04:28<10:08,  9.31it/s]

No person detected!

Processing b3ad:  31%|███       | 2553/8192 [04:31<10:30,  8.95it/s]

No person detected!

Processing b3ad:  31%|███       | 2556/8192 [04:31<11:11,  8.39it/s]

No person detected!

Processing b3ad:  31%|███       | 2559/8192 [04:32<10:13,  9.18it/s]

No person detected!

Processing b3ad:  31%|███▏      | 2578/8192 [04:34<11:13,  8.33it/s]

No person detected!

Processing b3ad:  32%|███▏      | 2581/8192 [04:34<10:08,  9.23it/s]

No person detected!

Processing b3ad:  32%|███▏      | 2594/8192 [04:36<10:07,  9.22it/s]

No person detected!

Processing b3ad:  33%|███▎      | 2664/8192 [04:43<09:56,  9.27it/s]

No person detected!

Processing b3ad:  33%|███▎      | 2689/8192 [04:46<09:35,  9.57it/s]

No person detected!

Processing b3ad:  33%|███▎      | 2697/8192 [04:47<09:58,  9.18it/s]

No person detected!

Processing b3ad:  33%|███▎      | 2700/8192 [04:47<09:54,  9.23it/s]

No person detected!

Processing b3ad:  33%|███▎      | 2703/8192 [04:48<09:30,  9.63it/s]

No person detected!
No person detected!

Processing b3ad:  33%|███▎      | 2712/8192 [04:49<09:26,  9.67it/s]

No person detected!

Processing b3ad:  33%|███▎      | 2716/8192 [04:49<09:22,  9.74it/s]

No person detected!

Processing b3ad:  33%|███▎      | 2722/8192 [04:50<09:19,  9.77it/s]

No person detected!
No person detected!

Processing b3ad:  33%|███▎      | 2726/8192 [04:50<09:30,  9.58it/s]

No person detected!

Processing b3ad:  33%|███▎      | 2728/8192 [04:50<09:16,  9.83it/s]

No person detected!

Processing b3ad:  33%|███▎      | 2735/8192 [04:51<09:22,  9.70it/s]

No person detected!

Processing b3ad:  33%|███▎      | 2738/8192 [04:51<09:21,  9.72it/s]

No person detected!

Processing b3ad:  34%|███▎      | 2747/8192 [04:52<09:36,  9.44it/s]

No person detected!

Processing b3ad:  34%|███▎      | 2759/8192 [04:53<09:17,  9.75it/s]

No person detected!
No person detected!

Processing b3ad:  34%|███▍      | 2767/8192 [04:54<09:35,  9.42it/s]

No person detected!

Processing b3ad:  34%|███▍      | 2777/8192 [04:55<09:33,  9.44it/s]

No person detected!

Processing b3ad:  34%|███▍      | 2782/8192 [04:56<09:23,  9.59it/s]

No person detected!

Processing b3ad:  34%|███▍      | 2788/8192 [04:57<09:30,  9.47it/s]

No person detected!
No person detected!

Processing b3ad:  34%|███▍      | 2795/8192 [04:57<09:34,  9.40it/s]

No person detected!

Processing b3ad:  34%|███▍      | 2809/8192 [04:59<09:26,  9.49it/s]

No person detected!
No person detected!

Processing b3ad:  35%|███▍      | 2830/8192 [05:01<09:02,  9.88it/s]

No person detected!

Processing b3ad:  35%|███▍      | 2835/8192 [05:02<09:19,  9.58it/s]

No person detected!

Processing b3ad:  35%|███▍      | 2851/8192 [05:03<08:58,  9.92it/s]

No person detected!

Processing b3ad:  35%|███▍      | 2854/8192 [05:04<09:19,  9.54it/s]

No person detected!

Processing b3ad:  35%|███▌      | 2871/8192 [05:05<09:21,  9.47it/s]

No person detected!

Processing b3ad:  35%|███▌      | 2875/8192 [05:06<09:12,  9.63it/s]

No person detected!

Processing b3ad:  35%|███▌      | 2884/8192 [05:07<09:24,  9.40it/s]

No person detected!

Processing b3ad:  36%|███▌      | 2911/8192 [05:10<09:17,  9.47it/s]

No person detected!

Processing b3ad:  36%|███▌      | 2934/8192 [05:12<09:03,  9.68it/s]

No person detected!

Processing b3ad:  36%|███▌      | 2942/8192 [05:13<09:20,  9.37it/s]

No person detected!

Processing b3ad:  36%|███▌      | 2948/8192 [05:14<09:29,  9.21it/s]

No person detected!

Processing b3ad:  36%|███▌      | 2964/8192 [05:15<09:14,  9.42it/s]

No person detected!

Processing b3ad:  36%|███▋      | 2977/8192 [05:17<09:03,  9.60it/s]

No person detected!

Processing b3ad:  37%|███▋      | 2996/8192 [05:19<08:53,  9.74it/s]

No person detected!

Processing b3ad:  37%|███▋      | 3000/8192 [05:19<09:08,  9.46it/s]

No person detected!

Processing b3ad:  37%|███▋      | 3005/8192 [05:20<08:51,  9.75it/s]

No person detected!

Processing b3ad:  37%|███▋      | 3019/8192 [05:21<08:50,  9.74it/s]

No person detected!

Processing b3ad:  37%|███▋      | 3028/8192 [05:22<08:50,  9.74it/s]

No person detected!

Processing b3ad:  37%|███▋      | 3055/8192 [05:25<09:33,  8.96it/s]

No person detected!

Processing b3ad:  37%|███▋      | 3068/8192 [05:26<08:54,  9.58it/s]

No person detected!

Processing b3ad:  38%|███▊      | 3087/8192 [05:29<09:15,  9.19it/s]

No person detected!
No person detected!

Processing b3ad:  38%|███▊      | 3092/8192 [05:29<09:01,  9.42it/s]

No person detected!

Processing b3ad:  38%|███▊      | 3117/8192 [05:32<08:48,  9.60it/s]

No person detected!

Processing b3ad:  38%|███▊      | 3125/8192 [05:33<08:56,  9.44it/s]

No person detected!
No person detected!

Processing b3ad:  38%|███▊      | 3130/8192 [05:33<08:40,  9.73it/s]

No person detected!
No person detected!

Processing b3ad:  38%|███▊      | 3137/8192 [05:34<08:50,  9.53it/s]

No person detected!

Processing b3ad:  38%|███▊      | 3140/8192 [05:34<09:00,  9.34it/s]

No person detected!

Processing b3ad:  38%|███▊      | 3143/8192 [05:35<08:54,  9.44it/s]

No person detected!

Processing b3ad:  38%|███▊      | 3151/8192 [05:35<08:38,  9.73it/s]

No person detected!

Processing b3ad:  39%|███▊      | 3156/8192 [05:36<08:35,  9.77it/s]

No person detected!

Processing b3ad:  39%|███▊      | 3166/8192 [05:37<08:53,  9.41it/s]

No person detected!
No person detected!

Processing b3ad:  39%|███▉      | 3177/8192 [05:38<08:48,  9.48it/s]

No person detected!

Processing b3ad:  39%|███▉      | 3182/8192 [05:39<08:52,  9.40it/s]

No person detected!

Processing b3ad:  39%|███▉      | 3223/8192 [05:43<08:31,  9.72it/s]

No person detected!
No person detected!

Processing b3ad:  39%|███▉      | 3227/8192 [05:43<08:45,  9.46it/s]

No person detected!

Processing b3ad:  39%|███▉      | 3234/8192 [05:44<08:44,  9.46it/s]

No person detected!

Processing b3ad:  40%|███▉      | 3242/8192 [05:45<08:47,  9.39it/s]

No person detected!

Processing b3ad:  40%|███▉      | 3255/8192 [05:47<08:53,  9.26it/s]

No person detected!

Processing b3ad:  40%|███▉      | 3270/8192 [05:48<08:40,  9.46it/s]

No person detected!

Processing b3ad:  40%|████      | 3290/8192 [05:50<08:59,  9.09it/s]

No person detected!

Processing b3ad:  40%|████      | 3304/8192 [05:52<08:43,  9.33it/s]

No person detected!

Processing b3ad:  41%|████      | 3331/8192 [05:55<08:35,  9.43it/s]

No person detected!

Processing b3ad:  41%|████      | 3336/8192 [05:55<08:20,  9.71it/s]

No person detected!
No person detected!

Processing b3ad:  41%|████      | 3346/8192 [05:56<08:13,  9.82it/s]

No person detected!

Processing b3ad:  41%|████      | 3349/8192 [05:57<08:54,  9.05it/s]

No person detected!

Processing b3ad:  41%|████      | 3352/8192 [05:57<08:38,  9.34it/s]

No person detected!

Processing b3ad:  41%|████      | 3354/8192 [05:57<08:32,  9.44it/s]

No person detected!

Processing b3ad:  41%|████      | 3359/8192 [05:58<08:20,  9.65it/s]

No person detected!

Processing b3ad:  41%|████      | 3364/8192 [05:58<08:05,  9.94it/s]

No person detected!
No person detected!

Processing b3ad:  41%|████      | 3369/8192 [05:59<08:10,  9.84it/s]

No person detected!
No person detected!

Processing b3ad:  41%|████      | 3374/8192 [05:59<08:25,  9.54it/s]

No person detected!

Processing b3ad:  41%|████      | 3376/8192 [06:00<08:20,  9.62it/s]

No person detected!
No person detected!

Processing b3ad:  41%|████▏     | 3392/8192 [06:01<08:27,  9.46it/s]

No person detected!

Processing b3ad:  41%|████▏     | 3396/8192 [06:02<08:15,  9.68it/s]

No person detected!

Processing b3ad:  42%|████▏     | 3404/8192 [06:03<08:26,  9.46it/s]

No person detected!
No person detected!

Processing b3ad:  42%|████▏     | 3406/8192 [06:03<08:40,  9.20it/s]

No person detected!

Processing b3ad:  42%|████▏     | 3410/8192 [06:03<08:41,  9.17it/s]

No person detected!

Processing b3ad:  42%|████▏     | 3412/8192 [06:03<08:31,  9.34it/s]

No person detected!

Processing b3ad:  42%|████▏     | 3414/8192 [06:04<08:46,  9.08it/s]

No person detected!

Processing b3ad:  42%|████▏     | 3417/8192 [06:04<08:44,  9.11it/s]

No person detected!
No person detected!

Processing b3ad:  42%|████▏     | 3423/8192 [06:05<08:20,  9.53it/s]

No person detected!

Processing b3ad:  42%|████▏     | 3444/8192 [06:07<08:04,  9.81it/s]

No person detected!
No person detected!

Processing b3ad:  42%|████▏     | 3446/8192 [06:07<07:51, 10.07it/s]

No person detected!
No person detected!

Processing b3ad:  42%|████▏     | 3453/8192 [06:08<08:07,  9.71it/s]

No person detected!

Processing b3ad:  42%|████▏     | 3463/8192 [06:09<08:43,  9.04it/s]

No person detected!

Processing b3ad:  42%|████▏     | 3480/8192 [06:11<08:36,  9.12it/s]

No person detected!

Processing b3ad:  43%|████▎     | 3487/8192 [06:12<08:14,  9.51it/s]

No person detected!

Processing b3ad:  43%|████▎     | 3494/8192 [06:12<08:22,  9.35it/s]

No person detected!
No person detected!

Processing b3ad:  43%|████▎     | 3498/8192 [06:13<08:19,  9.40it/s]

No person detected!

Processing b3ad:  43%|████▎     | 3506/8192 [06:14<08:38,  9.03it/s]

No person detected!

Processing b3ad:  43%|████▎     | 3510/8192 [06:14<08:25,  9.26it/s]

No person detected!

Processing b3ad:  43%|████▎     | 3524/8192 [06:16<08:04,  9.64it/s]

No person detected!
No person detected!

Processing b3ad:  43%|████▎     | 3544/8192 [06:18<08:10,  9.48it/s]

No person detected!

Processing b3ad:  44%|████▎     | 3571/8192 [06:21<08:01,  9.59it/s]

No person detected!

Processing b3ad:  44%|████▎     | 3573/8192 [06:21<08:16,  9.31it/s]

No person detected!

Processing b3ad:  44%|████▎     | 3576/8192 [06:21<08:37,  8.93it/s]

No person detected!

Processing b3ad:  44%|████▎     | 3583/8192 [06:22<07:56,  9.68it/s]

No person detected!
No person detected!

Processing b3ad:  44%|████▍     | 3601/8192 [06:24<08:03,  9.49it/s]

No person detected!

Processing b3ad:  44%|████▍     | 3611/8192 [06:25<07:56,  9.61it/s]

No person detected!

Processing b3ad:  44%|████▍     | 3616/8192 [06:25<07:51,  9.71it/s]

No person detected!

Processing b3ad:  44%|████▍     | 3618/8192 [06:26<07:52,  9.69it/s]

No person detected!
No person detected!

Processing b3ad:  44%|████▍     | 3634/8192 [06:27<08:06,  9.36it/s]

No person detected!
No person detected!

Processing b3ad:  44%|████▍     | 3637/8192 [06:28<08:06,  9.37it/s]

No person detected!
No person detected!

Processing b3ad:  44%|████▍     | 3645/8192 [06:29<08:13,  9.22it/s]

No person detected!

Processing b3ad:  45%|████▍     | 3681/8192 [06:32<07:56,  9.46it/s]

No person detected!

Processing b3ad:  45%|████▌     | 3687/8192 [06:33<08:01,  9.35it/s]

No person detected!

Processing b3ad:  45%|████▌     | 3692/8192 [06:34<07:46,  9.64it/s]

No person detected!
No person detected!

Processing b3ad:  46%|████▌     | 3736/8192 [06:38<07:50,  9.47it/s]

No person detected!

Processing b3ad:  46%|████▌     | 3750/8192 [06:40<07:49,  9.47it/s]

No person detected!

Processing b3ad:  46%|████▌     | 3758/8192 [06:41<07:50,  9.43it/s]

No person detected!
No person detected!

Processing b3ad:  46%|████▌     | 3761/8192 [06:41<07:47,  9.48it/s]

No person detected!

Processing b3ad:  46%|████▌     | 3773/8192 [06:42<07:45,  9.50it/s]

No person detected!

Processing b3ad:  46%|████▌     | 3776/8192 [06:43<08:01,  9.17it/s]

No person detected!

Processing b3ad:  46%|████▋     | 3798/8192 [06:45<07:57,  9.21it/s]

No person detected!

Processing b3ad:  46%|████▋     | 3806/8192 [06:46<07:31,  9.71it/s]

No person detected!

Processing b3ad:  47%|████▋     | 3827/8192 [06:48<08:10,  8.90it/s]

No person detected!

Processing b3ad:  47%|████▋     | 3848/8192 [06:50<07:42,  9.40it/s]

No person detected!

Processing b3ad:  47%|████▋     | 3858/8192 [06:52<07:44,  9.32it/s]

No person detected!

Processing b3ad:  47%|████▋     | 3865/8192 [06:52<07:31,  9.59it/s]

No person detected!

Processing b3ad:  47%|████▋     | 3870/8192 [06:53<07:29,  9.62it/s]

No person detected!
No person detected!

Processing b3ad:  47%|████▋     | 3873/8192 [06:53<07:16,  9.89it/s]

No person detected!

Processing b3ad:  47%|████▋     | 3876/8192 [06:53<07:29,  9.60it/s]

No person detected!

Processing b3ad:  47%|████▋     | 3882/8192 [06:54<07:27,  9.63it/s]

No person detected!

Processing b3ad:  47%|████▋     | 3886/8192 [06:55<07:40,  9.35it/s]

No person detected!
No person detected!

Processing b3ad:  47%|████▋     | 3890/8192 [06:55<07:30,  9.56it/s]

No person detected!

Processing b3ad:  48%|████▊     | 3893/8192 [06:55<07:31,  9.52it/s]

No person detected!

Processing b3ad:  48%|████▊     | 3900/8192 [06:56<07:36,  9.41it/s]

No person detected!
No person detected!

Processing b3ad:  48%|████▊     | 3911/8192 [06:57<07:41,  9.28it/s]

No person detected!

Processing b3ad:  48%|████▊     | 3923/8192 [06:58<07:34,  9.40it/s]

No person detected!
No person detected!

Processing b3ad:  48%|████▊     | 3933/8192 [07:00<07:34,  9.37it/s]

No person detected!

Processing b3ad:  48%|████▊     | 3942/8192 [07:00<07:32,  9.39it/s]

No person detected!

Processing b3ad:  48%|████▊     | 3948/8192 [07:01<07:20,  9.63it/s]

No person detected!

Processing b3ad:  48%|████▊     | 3953/8192 [07:02<07:24,  9.54it/s]

No person detected!

Processing b3ad:  48%|████▊     | 3956/8192 [07:02<07:35,  9.31it/s]

No person detected!

Processing b3ad:  48%|████▊     | 3965/8192 [07:03<07:16,  9.68it/s]

No person detected!
No person detected!

Processing b3ad:  48%|████▊     | 3969/8192 [07:03<07:14,  9.71it/s]

No person detected!

Processing b3ad:  49%|████▊     | 3982/8192 [07:05<07:31,  9.33it/s]

No person detected!

Processing b3ad:  49%|████▊     | 3986/8192 [07:05<07:20,  9.56it/s]

No person detected!

Processing b3ad:  49%|████▉     | 4011/8192 [07:08<07:26,  9.37it/s]

No person detected!

Processing b3ad:  49%|████▉     | 4017/8192 [07:09<07:16,  9.56it/s]

No person detected!

Processing b3ad:  49%|████▉     | 4034/8192 [07:10<07:33,  9.16it/s]

No person detected!

Processing b3ad:  49%|████▉     | 4043/8192 [07:11<07:51,  8.80it/s]

No person detected!

Processing b3ad:  50%|████▉     | 4061/8192 [07:13<07:21,  9.35it/s]

No person detected!

Processing b3ad:  50%|████▉     | 4068/8192 [07:14<07:17,  9.43it/s]

No person detected!

Processing b3ad:  50%|████▉     | 4071/8192 [07:14<07:10,  9.57it/s]

No person detected!

Processing b3ad:  50%|█████     | 4131/8192 [07:21<07:16,  9.31it/s]

No person detected!

Processing b3ad:  52%|█████▏    | 4226/8192 [07:32<07:01,  9.40it/s]

No person detected!

Processing b3ad:  52%|█████▏    | 4272/8192 [07:37<07:09,  9.13it/s]

No person detected!

Processing b3ad:  52%|█████▏    | 4300/8192 [07:40<07:00,  9.26it/s]

No person detected!

Processing b3ad:  53%|█████▎    | 4323/8192 [07:42<07:12,  8.94it/s]

No person detected!

Processing b3ad:  54%|█████▎    | 4400/8192 [07:51<07:06,  8.90it/s]

No person detected!

Processing b3ad:  55%|█████▌    | 4506/8192 [08:03<07:11,  8.54it/s]

No person detected!

Processing b3ad:  55%|█████▌    | 4544/8192 [08:08<06:44,  9.01it/s]

No person detected!

Processing b3ad:  56%|█████▌    | 4560/8192 [08:10<06:53,  8.78it/s]

No person detected!

Processing b3ad:  56%|█████▌    | 4582/8192 [08:12<06:46,  8.89it/s]

No person detected!

Processing b3ad:  56%|█████▌    | 4594/8192 [08:14<06:41,  8.97it/s]

No person detected!
No person detected!

Processing b3ad:  57%|█████▋    | 4641/8192 [08:19<06:46,  8.73it/s]

No person detected!

Processing b3ad:  57%|█████▋    | 4696/8192 [08:26<07:02,  8.28it/s]

No person detected!

Processing b3ad:  58%|█████▊    | 4717/8192 [08:28<06:26,  8.99it/s]

No person detected!

Processing b3ad:  58%|█████▊    | 4730/8192 [08:29<06:37,  8.70it/s]

No person detected!

Processing b3ad:  58%|█████▊    | 4750/8192 [08:32<06:38,  8.63it/s]

No person detected!

Processing b3ad:  58%|█████▊    | 4765/8192 [08:34<06:34,  8.69it/s]

No person detected!

Processing b3ad:  58%|█████▊    | 4767/8192 [08:34<06:51,  8.32it/s]

No person detected!

Processing b3ad:  59%|█████▊    | 4809/8192 [08:39<06:23,  8.82it/s]

No person detected!

Processing b3ad:  60%|█████▉    | 4914/8192 [08:51<05:52,  9.29it/s]

No person detected!

Processing b3ad:  60%|██████    | 4942/8192 [08:54<06:16,  8.63it/s]

No person detected!

Processing b3ad:  60%|██████    | 4946/8192 [08:54<06:25,  8.41it/s]

No person detected!

Processing b3ad:  61%|██████    | 4980/8192 [08:59<06:13,  8.61it/s]

No person detected!

Processing b3ad:  61%|██████    | 4992/8192 [09:00<06:03,  8.80it/s]

No person detected!

Processing b3ad:  61%|██████    | 5014/8192 [09:02<05:44,  9.22it/s]

No person detected!

Processing b3ad:  62%|██████▏   | 5069/8192 [09:09<05:44,  9.07it/s]

No person detected!

Processing b3ad:  63%|██████▎   | 5130/8192 [09:16<06:05,  8.38it/s]

No person detected!

Processing b3ad:  63%|██████▎   | 5179/8192 [09:22<05:39,  8.88it/s]

No person detected!

Processing b3ad:  63%|██████▎   | 5182/8192 [09:22<05:27,  9.20it/s]

No person detected!

Processing b3ad:  63%|██████▎   | 5186/8192 [09:22<05:38,  8.89it/s]

No person detected!

Processing b3ad:  64%|██████▎   | 5208/8192 [09:25<05:29,  9.04it/s]

No person detected!

Processing b3ad:  64%|██████▍   | 5247/8192 [09:30<06:03,  8.11it/s]

No person detected!

Processing b3ad:  65%|██████▌   | 5362/8192 [09:43<05:32,  8.52it/s]

No person detected!

Processing b3ad:  66%|██████▌   | 5389/8192 [09:46<05:18,  8.81it/s]

No person detected!

Processing b3ad:  66%|██████▋   | 5433/8192 [09:51<05:19,  8.64it/s]

No person detected!

Processing b3ad:  67%|██████▋   | 5482/8192 [09:57<04:59,  9.04it/s]

No person detected!
No person detected!

Processing b3ad:  67%|██████▋   | 5515/8192 [10:01<05:21,  8.33it/s]

No person detected!

Processing b3ad:  68%|██████▊   | 5560/8192 [10:06<05:00,  8.75it/s]

No person detected!

Processing b3ad:  68%|██████▊   | 5570/8192 [10:08<05:02,  8.68it/s]

No person detected!

Processing b3ad:  68%|██████▊   | 5600/8192 [10:11<05:20,  8.08it/s]

No person detected!

Processing b3ad:  69%|██████▉   | 5662/8192 [10:19<04:43,  8.93it/s]

No person detected!

Processing b3ad:  70%|██████▉   | 5706/8192 [10:24<04:57,  8.36it/s]

No person detected!

Processing b3ad:  72%|███████▏  | 5890/8192 [10:46<04:25,  8.67it/s]

No person detected!

Processing b3ad:  73%|███████▎  | 5951/8192 [10:54<04:47,  7.79it/s]

No person detected!

Processing b3ad:  73%|███████▎  | 5957/8192 [10:54<04:21,  8.54it/s]

No person detected!

Processing b3ad:  73%|███████▎  | 5968/8192 [10:56<04:00,  9.24it/s]

No person detected!
No person detected!

Processing b3ad:  73%|███████▎  | 5979/8192 [10:57<04:17,  8.58it/s]

No person detected!

Processing b3ad:  73%|███████▎  | 5983/8192 [10:57<04:07,  8.92it/s]

No person detected!

Processing b3ad:  73%|███████▎  | 5986/8192 [10:58<04:05,  9.00it/s]

No person detected!

Processing b3ad:  73%|███████▎  | 6002/8192 [10:59<04:05,  8.91it/s]

No person detected!

Processing b3ad:  74%|███████▎  | 6038/8192 [11:04<04:12,  8.54it/s]

No person detected!

Processing b3ad:  75%|███████▍  | 6120/8192 [11:14<03:53,  8.88it/s]

No person detected!

Processing b3ad:  75%|███████▍  | 6124/8192 [11:14<03:58,  8.66it/s]

No person detected!

Processing b3ad:  75%|███████▍  | 6129/8192 [11:15<04:12,  8.18it/s]

No person detected!

Processing b3ad:  75%|███████▍  | 6132/8192 [11:15<03:58,  8.64it/s]

No person detected!

Processing b3ad:  84%|████████▍ | 6888/8192 [12:43<02:22,  9.14it/s]

No person detected!

Processing b3ad:  85%|████████▍ | 6938/8192 [12:49<02:18,  9.04it/s]

No person detected!

Processing b3ad:  86%|████████▌ | 7049/8192 [13:01<02:05,  9.10it/s]

No person detected!

Processing b3ad:  86%|████████▋ | 7069/8192 [13:03<02:07,  8.81it/s]

No person detected!

Processing b3ad:  87%|████████▋ | 7096/8192 [13:07<02:09,  8.48it/s]

No person detected!

Processing b3ad:  87%|████████▋ | 7115/8192 [13:09<01:55,  9.34it/s]

No person detected!

Processing b3ad:  88%|████████▊ | 7230/8192 [13:22<01:44,  9.20it/s]

No person detected!

Processing b3ad:  91%|█████████ | 7441/8192 [13:46<01:23,  8.97it/s]

No person detected!

Processing b3ad:  91%|█████████ | 7444/8192 [13:46<01:22,  9.08it/s]

No person detected!

Processing b3ad:  92%|█████████▏| 7499/8192 [13:52<01:14,  9.31it/s]

No person detected!

Processing b3ad:  92%|█████████▏| 7518/8192 [13:54<01:13,  9.18it/s]

No person detected!

Processing b3ad:  92%|█████████▏| 7557/8192 [13:59<01:12,  8.71it/s]

No person detected!

Processing b3ad:  92%|█████████▏| 7563/8192 [13:59<01:08,  9.15it/s]

No person detected!

Processing b3ad:  92%|█████████▏| 7574/8192 [14:00<01:07,  9.18it/s]

No person detected!

Processing b3ad:  93%|█████████▎| 7605/8192 [14:04<01:03,  9.24it/s]

No person detected!

Processing b3ad:  93%|█████████▎| 7629/8192 [14:07<01:04,  8.80it/s]

No person detected!

Processing b3ad:  94%|█████████▎| 7664/8192 [14:11<00:56,  9.37it/s]

No person detected!

Processing b3ad:  94%|█████████▎| 7670/8192 [14:11<00:56,  9.28it/s]

No person detected!

Processing b3ad:  94%|█████████▎| 7676/8192 [14:12<00:57,  8.94it/s]

No person detected!

Processing b3ad:  95%|█████████▌| 7801/8192 [14:26<00:41,  9.41it/s]

No person detected!

Processing b3ad:  97%|█████████▋| 7943/8192 [14:42<00:27,  9.06it/s]

No person detected!

Processing b3ad:  97%|█████████▋| 7964/8192 [14:44<00:24,  9.36it/s]

No person detected!

Processing b3ad:  97%|█████████▋| 7977/8192 [14:46<00:23,  9.19it/s]

No person detected!

Processing b3ad:  97%|█████████▋| 7981/8192 [14:46<00:23,  8.89it/s]

No person detected!

Processing b3ad:  98%|█████████▊| 8050/8192 [14:54<00:15,  9.46it/s]

No person detected!

Processing b3ad:  99%|█████████▊| 8080/8192 [14:57<00:11,  9.46it/s]

No person detected!

Processing b3ad: 100%|█████████▉| 8154/8192 [15:05<00:04,  9.41it/s]

No person detected!

Processing b3ad: 100%|██████████| 8192/8192 [15:10<00:00,  9.00it/s]

Total Cumulative Inference Time: 483.7231 seconds
Average per sample: 61.63 ms

In [9]:
print(df.info(verbose=True, show_counts=True))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8192 entries, 0 to 8191
Data columns (total 84 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            8192 non-null   object
 1   actor         8192 non-null   object
 2   pose          8192 non-null   float64
 3   cam_pitch     8192 non-null   float64
 4   gt_dist       8192 non-null   float64
 5   gt_ang_sep    8192 non-null   float64
 6   gt_d_yaw      8192 non-null   float64
 7   gt_d_pitch    8192 non-null   float64
 8   gt_sw_x       8192 non-null   float64
 9   gt_sw_y       8192 non-null   float64
 10  gt_sw_z       8192 non-null   float64
 11  gt_sc_x       8192 non-null   float64
 12  gt_sc_y       8192 non-null   float64
 13  gt_sc_z       8192 non-null   float64
 14  b3ad_dist     7849 non-null   float64
 15  b3ad_ang_sep  7849 non-null   float64
 16  b3ad_d_yaw    7849 non-null   float64
 17  b3ad_d_pitch  7849 non-null   float64
 18  b3ad_sw_x     7849 non-null   float64
 19  b3ad_sw_y     7849 non-null   float64
 20  b3ad_sw_z     7849 non-null   float64
 21  b3ad_sc_x     7849 non-null   float64
 22  b3ad_sc_y     7849 non-null   float64
 23  b3ad_sc_z     7849 non-null   float64
 24  b3sd_dist     7323 non-null   float64
 25  b3sd_ang_sep  7323 non-null   float64
 26  b3sd_d_yaw    7323 non-null   float64
 27  b3sd_d_pitch  7323 non-null   float64
 28  b3sd_sw_x     7323 non-null   float64
 29  b3sd_sw_y     7323 non-null   float64
 30  b3sd_sw_z     7323 non-null   float64
 31  b3sd_sc_x     7323 non-null   float64
 32  b3sd_sc_y     7323 non-null   float64
 33  b3sd_sc_z     7323 non-null   float64
 34  m3ad_dist     4616 non-null   float64
 35  m3ad_ang_sep  4616 non-null   float64
 36  m3ad_d_yaw    4616 non-null   float64
 37  m3ad_d_pitch  4616 non-null   float64
 38  m3ad_sw_x     4616 non-null   float64
 39  m3ad_sw_y     4616 non-null   float64
 40  m3ad_sw_z     4616 non-null   float64
 41  m3ad_sc_x     4616 non-null   float64
 42  m3ad_sc_y     4616 non-null   float64
 43  m3ad_sc_z     4616 non-null   float64
 44  m3sd_dist     4571 non-null   float64
 45  m3sd_ang_sep  4571 non-null   float64
 46  m3sd_d_yaw    4571 non-null   float64
 47  m3sd_d_pitch  4571 non-null   float64
 48  m3sd_sw_x     4571 non-null   float64
 49  m3sd_sw_y     4571 non-null   float64
 50  m3sd_sw_z     4571 non-null   float64
 51  m3sd_sc_x     4571 non-null   float64
 52  m3sd_sc_y     4571 non-null   float64
 53  m3sd_sc_z     4571 non-null   float64
 54  m3pa_dist     4616 non-null   float64
 55  m3pa_ang_sep  4616 non-null   float64
 56  m3pa_d_yaw    4616 non-null   float64
 57  m3pa_d_pitch  4616 non-null   float64
 58  m3pa_sw_x     4616 non-null   float64
 59  m3pa_sw_y     4616 non-null   float64
 60  m3pa_sw_z     4616 non-null   float64
 61  m3pa_sc_x     4616 non-null   float64
 62  m3pa_sc_y     4616 non-null   float64
 63  m3pa_sc_z     4616 non-null   float64
 64  m2as_dist     4378 non-null   float64
 65  m2as_ang_sep  4378 non-null   float64
 66  m2as_d_yaw    4378 non-null   float64
 67  m2as_d_pitch  4378 non-null   float64
 68  m2as_sw_x     4378 non-null   float64
 69  m2as_sw_y     4378 non-null   float64
 70  m2as_sw_z     4378 non-null   float64
 71  m2as_sc_x     4378 non-null   float64
 72  m2as_sc_y     4378 non-null   float64
 73  m2as_sc_z     4378 non-null   float64
 74  m2st_dist     4088 non-null   float64
 75  m2st_ang_sep  4088 non-null   float64
 76  m2st_d_yaw    4088 non-null   float64
 77  m2st_d_pitch  4088 non-null   float64
 78  m2st_sw_x     4088 non-null   float64
 79  m2st_sw_y     4088 non-null   float64
 80  m2st_sw_z     4088 non-null   float64
 81  m2st_sc_x     4088 non-null   float64
 82  m2st_sc_y     4088 non-null   float64
 83  m2st_sc_z     4088 non-null   float64
dtypes: float64(82), object(2)
memory usage: 5.3+ MB
None

In [10]:
pd.set_option('display.max_columns', None)
df.head(10)

,id,actor,pose,cam_pitch,gt_dist,gt_ang_sep,gt_d_yaw,gt_d_pitch,gt_sw_x,gt_sw_y,gt_sw_z,gt_sc_x,gt_sc_y,gt_sc_z,b3ad_dist,b3ad_ang_sep,b3ad_d_yaw,b3ad_d_pitch,b3ad_sw_x,b3ad_sw_y,b3ad_sw_z,b3ad_sc_x,b3ad_sc_y,b3ad_sc_z,b3sd_dist,b3sd_ang_sep,b3sd_d_yaw,b3sd_d_pitch,b3sd_sw_x,b3sd_sw_y,b3sd_sw_z,b3sd_sc_x,b3sd_sc_y,b3sd_sc_z,m3ad_dist,m3ad_ang_sep,m3ad_d_yaw,m3ad_d_pitch,m3ad_sw_x,m3ad_sw_y,m3ad_sw_z,m3ad_sc_x,m3ad_sc_y,m3ad_sc_z,m3sd_dist,m3sd_ang_sep,m3sd_d_yaw,m3sd_d_pitch,m3sd_sw_x,m3sd_sw_y,m3sd_sw_z,m3sd_sc_x,m3sd_sc_y,m3sd_sc_z,m3pa_dist,m3pa_ang_sep,m3pa_d_yaw,m3pa_d_pitch,m3pa_sw_x,m3pa_sw_y,m3pa_sw_z,m3pa_sc_x,m3pa_sc_y,m3pa_sc_z,m2as_dist,m2as_ang_sep,m2as_d_yaw,m2as_d_pitch,m2as_sw_x,m2as_sw_y,m2as_sw_z,m2as_sc_x,m2as_sc_y,m2as_sc_z,m2st_dist,m2st_ang_sep,m2st_d_yaw,m2st_d_pitch,m2st_sw_x,m2st_sw_y,m2st_sw_z,m2st_sc_x,m2st_sc_y,m2st_sc_z
0,00001,BP_Ada_C_1,34.0,-6.287881,354.167297,14.391177,-4.068234,13.838668,-0.968621,0.066612,0.239448,-1.0,8.827433e-16,2.006235e-17,585.174945,39.345997,-29.096792,28.461256,-0.800313,0.388789,0.456446,-0.999042,-0.027048,-0.034394,316.049377,36.840027,-27.542477,26.487944,-0.800313,0.388789,0.456446,-1.0,0.0,0.0,637.021029,14.850775,-15.034202,0.433168,-0.969154,0.240048,0.055837,-0.998849,-0.016484,0.045054,339.393950,14.267933,-14.078275,3.014588,-0.969154,0.240048,0.055837,-1.0,0.0,0.0,401.922641,13.923945,-10.698299,9.124849,-0.971876,0.182471,0.148867,-0.999926,0.003082,-0.011759,339.393950,6.288336,-2.309619,5.860942,-0.993983,0.039397,0.102201,-1.0,0.0,0.0,337.681453,160.060166,-172.649296,7.383960,0.935750,0.127283,0.328893,-0.999921,-0.002682,-0.012263
1,00002,BP_Ada_C_1,17.0,-80.392527,839.159817,70.426628,10.291927,-70.265796,-0.335014,-0.175880,-0.925652,-1.0,-1.058414e-17,3.386925e-17,1913.251864,109.699960,11.003982,-109.546262,0.327019,-0.159929,-0.931387,-0.999943,0.001403,0.010596,831.940552,109.087953,10.489977,-108.939461,0.327019,-0.159929,-0.931387,-1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00003,BP_Ada_C_1,114.0,-50.585528,716.956094,30.322529,-20.436334,29.535145,-0.863197,0.059908,0.501300,-1.0,2.477637e-18,-7.928438e-17,1704.993278,169.140734,-166.090185,-94.061589,0.979394,0.180510,0.090572,-0.999849,-0.008058,-0.015365,706.067810,168.348489,-165.376296,-94.944170,0.979394,0.180510,0.090572,-1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00004,BP_Ada_C_1,42.0,-20.623707,357.440408,61.804887,-68.575333,9.502579,-0.472476,0.805154,0.358460,-1.0,3.975727e-17,3.975727e-17,671.772309,62.328035,-67.859639,8.661009,-0.493566,0.814348,0.305337,-0.999181,-0.022767,-0.033448,361.144714,60.424761,-66.482342,6.738699,-0.493566,0.814348,0.305337,-1.0,0.0,0.0,347.132425,83.777625,-86.829968,-9.904850,-0.116742,0.983634,0.137240,-0.999842,-0.006147,-0.016684,353.870463,83.295862,-86.455927,-10.861209,-0.116742,0.983634,0.137240,-1.0,0.0,0.0,403.813095,82.465868,-85.778881,-8.537320,-0.137887,0.978990,0.150222,-0.999780,-0.003718,-0.020634,353.870463,111.220525,-115.556863,-14.220504,0.361959,0.896530,0.255383,-1.0,0.0,0.0,386.860524,16.545744,-17.400630,3.438862,-0.960390,0.272383,0.058802,-0.999872,-0.002752,-0.015739
4,00005,BP_Ada_C_1,114.0,-16.400097,540.643029,72.647749,82.989366,63.720576,-0.298245,-0.170291,0.939176,-1.0,1.577106e-16,1.051404e-16,738.493714,92.781332,119.979303,44.300243,0.017631,-0.451204,0.892247,-0.999042,-0.013678,-0.041560,535.244934,91.010260,120.787070,41.916798,0.017631,-0.451204,0.892247,-1.0,0.0,0.0,542.156821,59.253452,50.104056,48.555979,-0.519870,-0.336814,0.785043,-0.999870,-0.007647,-0.014186,533.333349,58.676487,50.558918,47.742675,-0.519870,-0.336814,0.785043,-1.0,0.0,0.0,566.978247,108.351796,145.538318,-33.927799,-0.302032,0.365970,-0.880252,0.999857,0.004209,0.016361,533.333349,112.678508,155.844909,30.937424,0.385560,-0.277311,0.880024,-1.0,0.0,0.0,483.475293,165.921985,175.796565,-18.033845,0.967381,-0.071326,0.243077,-0.999933,-0.001848,-0.011442
5,00006,BP_Ada_C_1,92.0,-67.072543,511.871710,35.985887,-115.477473,3.051334,-0.809162,0.306925,0.501053,-1.0,-2.082190e-17,-5.552506e-17,1534.161531,63.127304,-99.797870,-32.114511,-0.457691,0.817597,0.349363,-0.999826,0.001096,-0.018599,506.214722,62.761751,-99.952271,-33.180273,-0.457692,0.817596,0.349363,-1.0,0.0,0.0,1256.007345,115.512248,-137.822760,-74.508567,0.412396,0.685860,0.599605,-0.999785,-0.012130,-0.016806,504.504538,114.355451,-136.107103,-75.481126,0.412396,0.685860,0.599605,-1.0,0.0,0.0,638.019084,81.870989,-127.332463,42.733514,0.157581,-0.741747,-0.651904,0.999856,0.009327,0.014171,504.504538,19.015820,-54.285084,4.327885,-0.945429,0.258967,0.197739,-1.0,0.0,0.0,452.631735,175.191351,-172.912755,-127.839991,0.994123,0.070675,0.081999,-0.999674,-0.011433,-0.022845
6,00007,BP_Ada_C_1,115.0,-58.337415,573.534355,30.892326,77.429488,21.783261,-0.858134,-0.167461,0.485349,-1.0,1.378259e-16,1.982215e-16,995.070274,76.233570,46.385530,-66.094685,-0.225153,-0.707567,-0.669817,-0.999666,0.005671,-0.025230,562.460815,76.988042,45.790619,-67.541779,-0.225154,-0.707567,-0.669817,-1.0,0.0,0.0,822.190601,34.329966,93.146021,17.330402,-0.817285,-0.236138,0.525627,-0.999869,-0.011744,0.011133,565.656567,35.186024,94.451448,17.961757,-0.817285,-0.236138,0.525627,-1.0,0.0,0.0,789.144230,141.161604,161.293836,79.666919,-0.777007,0.292225,-0.557553,0.999980,0.003542,0.005313,565.656567,23.234888,43.675699,17.238140,-0.918895,-0.172025,0.355020,-1.0,0.0,0.0,630.444949,8.157476,8.274880,7.165474,-0.990463,-0.060733,0.123671,-0.999988,-0.000535,-0.004866
7,00008,BP_Ada_C_1,65.0,-83.698078,893.154696,40.795695,-94.703134,-33.572474,-0.757044,0.638948,0.136490,-1.0,-2.386628e-17,3.500388e-16,2046.226095,81.025875,23.559446,-80.425716,-0.148040,-0.267501,-0.952117,-0.999762,0.017339,-0.013257,899.598389,81.486619,15.530103,-81.254581,-0.148040,-0.267501,-0.952117,-1.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,00009,BP_Ada_C_1,4.0,-17.160619,582.529679,90.029656,-90.070230,-17.033701,0.000518,0.999997,0.002478,-1.0,0.000000e+00,9.758030e-17,969.385163,76.166902,-70.462317,-31.006358,-0.240597,0.904900,-0.351097,-0.999595,-0.011635,-0.025986,583.333374,76.078194,-69.769896,-32.496580,-0.240597,0.904900,-0.351097,-1.0,0.0,0.0,545.917287,86.839673,-79.581904,-38.431548,-0.054264,0.909512,-0.412119,-0.999850,-0.006345,-0.016123,583.333349,86.889360,-79.203276,-39.355726,-0.054264,0.909512,-0.412119,-1.0,0.0,0.0,603.538187,88.701394,-82.475832,-36.207874,-0.018360,0.931554,-0.363138,-0.999868,-0.001667,-0.016132,583.333349,109.628775,-105.600767,-35.264736,0.335925,0.915476,-0.221490,-1.0,0.0,0.0,570.897692,24.931222,-24.471015,-7.284804,-0.905390,0.408844,-0.114521,-0.999902,-0.000218,-0.013990
9,00010,BP_Ada_C_1,63.0,-12.268837,727.370530,37.593015,28.693427,27.857188,-0.792364,-0.367116,0.487222,-1.0,2.344476e-16,0.000000e+00,1212.800294,44.279952,36.991295,30.176196,-0.728645,-0.450227,0.516112,-0.999771,0.003667,-0.021100,1166.666748,43.227048,36.777194,28.967067,-0.728645,-0.450227,0.516112,-1.0,0.0,0.0,1078.281027,20.779904,19.248223,9.956668,-0.928465,-0.311714,0.201956,-0.999793,-0.009901,0.017780,717.948723,21.803163,19.831148,10.974806,-0.928465,-0.311714,0.201956,-1.0,0.0,0.0,744.170564,31.359615,28.599728,16.424969,-0.855138,-0.424476,0.297588,-0.999957,-0.003287,-0.008667,717.948723,33.639835,29.439372,20.097587,-0.832536,-0.415143,0.366796,-1.0,0.0,0.0,616.070801,173.441593,174.779712,-19.779935,0.993352,-0.086310,0.076174,-0.999975,-0.003789,-0.005986

In [11]:
# Save Dataframe

df.to_csv(SAVE_PATH, index=False)

In [12]:
# Sanity Check

check_df = pd.read_csv(SAVE_PATH, dtype={'id': str})
print(check_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8192 entries, 0 to 8191
Data columns (total 84 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            8192 non-null   object
 1   actor         8192 non-null   object
 2   pose          8192 non-null   float64
 3   cam_pitch     8192 non-null   float64
 4   gt_dist       8192 non-null   float64
 5   gt_ang_sep    8192 non-null   float64
 6   gt_d_yaw      8192 non-null   float64
 7   gt_d_pitch    8192 non-null   float64
 8   gt_sw_x       8192 non-null   float64
 9   gt_sw_y       8192 non-null   float64
 10  gt_sw_z       8192 non-null   float64
 11  gt_sc_x       8192 non-null   float64
 12  gt_sc_y       8192 non-null   float64
 13  gt_sc_z       8192 non-null   float64
 14  b3ad_dist     7849 non-null   float64
 15  b3ad_ang_sep  7849 non-null   float64
 16  b3ad_d_yaw    7849 non-null   float64
 17  b3ad_d_pitch  7849 non-null   float64
 18  b3ad_sw_x     7849 non-null   float64
 19  b3ad_sw_y     7849 non-null   float64
 20  b3ad_sw_z     7849 non-null   float64
 21  b3ad_sc_x     7849 non-null   float64
 22  b3ad_sc_y     7849 non-null   float64
 23  b3ad_sc_z     7849 non-null   float64
 24  b3sd_dist     7323 non-null   float64
 25  b3sd_ang_sep  7323 non-null   float64
 26  b3sd_d_yaw    7323 non-null   float64
 27  b3sd_d_pitch  7323 non-null   float64
 28  b3sd_sw_x     7323 non-null   float64
 29  b3sd_sw_y     7323 non-null   float64
 30  b3sd_sw_z     7323 non-null   float64
 31  b3sd_sc_x     7323 non-null   float64
 32  b3sd_sc_y     7323 non-null   float64
 33  b3sd_sc_z     7323 non-null   float64
 34  m3ad_dist     4616 non-null   float64
 35  m3ad_ang_sep  4616 non-null   float64
 36  m3ad_d_yaw    4616 non-null   float64
 37  m3ad_d_pitch  4616 non-null   float64
 38  m3ad_sw_x     4616 non-null   float64
 39  m3ad_sw_y     4616 non-null   float64
 40  m3ad_sw_z     4616 non-null   float64
 41  m3ad_sc_x     4616 non-null   float64
 42  m3ad_sc_y     4616 non-null   float64
 43  m3ad_sc_z     4616 non-null   float64
 44  m3sd_dist     4571 non-null   float64
 45  m3sd_ang_sep  4571 non-null   float64
 46  m3sd_d_yaw    4571 non-null   float64
 47  m3sd_d_pitch  4571 non-null   float64
 48  m3sd_sw_x     4571 non-null   float64
 49  m3sd_sw_y     4571 non-null   float64
 50  m3sd_sw_z     4571 non-null   float64
 51  m3sd_sc_x     4571 non-null   float64
 52  m3sd_sc_y     4571 non-null   float64
 53  m3sd_sc_z     4571 non-null   float64
 54  m3pa_dist     4616 non-null   float64
 55  m3pa_ang_sep  4616 non-null   float64
 56  m3pa_d_yaw    4616 non-null   float64
 57  m3pa_d_pitch  4616 non-null   float64
 58  m3pa_sw_x     4616 non-null   float64
 59  m3pa_sw_y     4616 non-null   float64
 60  m3pa_sw_z     4616 non-null   float64
 61  m3pa_sc_x     4616 non-null   float64
 62  m3pa_sc_y     4616 non-null   float64
 63  m3pa_sc_z     4616 non-null   float64
 64  m2as_dist     4378 non-null   float64
 65  m2as_ang_sep  4378 non-null   float64
 66  m2as_d_yaw    4378 non-null   float64
 67  m2as_d_pitch  4378 non-null   float64
 68  m2as_sw_x     4378 non-null   float64
 69  m2as_sw_y     4378 non-null   float64
 70  m2as_sw_z     4378 non-null   float64
 71  m2as_sc_x     4378 non-null   float64
 72  m2as_sc_y     4378 non-null   float64
 73  m2as_sc_z     4378 non-null   float64
 74  m2st_dist     4088 non-null   float64
 75  m2st_ang_sep  4088 non-null   float64
 76  m2st_d_yaw    4088 non-null   float64
 77  m2st_d_pitch  4088 non-null   float64
 78  m2st_sw_x     4088 non-null   float64
 79  m2st_sw_y     4088 non-null   float64
 80  m2st_sw_z     4088 non-null   float64
 81  m2st_sc_x     4088 non-null   float64
 82  m2st_sc_y     4088 non-null   float64
 83  m2st_sc_z     4088 non-null   float64
dtypes: float64(82), object(2)
memory usage: 5.3+ MB
None